# import csv
# import random
# from opencage.geocoder import OpenCageGeocode

# def generate_random_"email"("name"):
#     domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com', 'example.com']  # Add more domains if needed
#     "name"_parts = "name".lower().split()
#     user"name" = ''.join("name"_parts) + str(random.randint(1, 999))
#     domain = random.choice(domains)
#     return f"{user"name"}@{domain}"

# def read_csv_to_array_of_dicts(csv_file, limit=349):
#     array_of_dicts = []
#     count_variable = 0
#     with open(csv_file, 'r') as file:
#         reader = csv.DictReader(file)
#         for i, row in enumerate(reader):
#             if i >= limit:
#                 break
#             cleaned_row = {k: v for k, v in row.items() if k != ''}  # Remove entries with empty string keys
            
#             # Add '"type"' key with random value
#             cleaned_row['"type"'] = random.choice(['hot', 'cold'])  
#             cleaned_row['"image"'] = "/images/warehouse_1.jpg"
#             lat_lng = cleaned_row.pop('"location"', '').split(',')
#             cleaned_row['"location"'] = [float(lat_lng[0]), float(lat_lng[1])]
#             cleaned_row['"price"'] = random.randint(1000, 5000)
            
#             # Add random "email" using "name"
#             cleaned_row['"email"'] = generate_random_"email"(cleaned_row['"name"'])
         
#             array_of_dicts.append(cleaned_row)
#             count_variable += 1
#     print(count_variable)
#     return array_of_dicts

# def write_data_to_js(data, js_file):
#     with open(js_file, 'w') as file:
#         file.write("const warehouseDetailData = ")
#         file.write(str(data))

# if __"name"__ == "__main__":
#     csv_file = 'Registered Warehouses - WDRA.csv'
#     data = read_csv_to_array_of_dicts(csv_file, limit=349)

#     js_file = 'warehouse_details.js'
#     write_data_to_js(data, js_file)

# Provided array of crop "name"s
crops_array = ['apple', 'grapes', 'chickpea', 'kidneybeans', 'pigeonpeas', 'mothbeans', 'coconut', 'banana', 'watermelon', 'muskmelon', 'coffee', 'papaya', 'pomegranate', 'blackgram', 'rice', 'maize', 'mango', 'orange', 'cotton', 'lentil', 'mungbean', 'jute']
# 
# # List to store crop dictionaries
# crops_"type"_list = []

# # Iterate over each crop "name" and create a dictionary with id, label, and "image"
# for i, crop_"name" in enumerate(crops_array):
#     crop_object = {
#         'id': i + 1,  # id starts from 1
#         'label': crop_"name",
#         '"image"': f'/"image"s/crop/{i + 1}.jpeg'  # Assuming "image"s are "name"d sequentially
#     }
#     crops_"type"_list.append(crop_object)

# print(crops_"type"_list)
import json
import random
import string

# Assume warehouseDetailData already contains the data
# Define warehouseDetailData
warehouseDetailData = [
    {
    "_id": "6751143",
    "ownerName": "A.P.M.C.MALKAPUR",
    "name": "APMC MALKAPUR",
    "address": "BELAD YARD ,MALKAPUR,",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "04-Jul-23",
    "registrationValidUpto": "03-Jul-28",
    "phoneNo": "9960783901",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.2746815, 74.1886849],
    "price": 3639,
    "email": "apmcmalkapur735@gmail.com",
  },
  {
    "ownerName": "AGRICULTURAL PRODUCE MARKET COMMITTEE",
    "name": "KRUSHI UTTPANA BAZAR SAMITI TULJAPUR",
    "_id": "6763296",
    "address": "Latur road Market yard,",
    "city": "Osmanabad",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "27-Jul-23",
    "registrationValidUpto": "26-Jul-28",
    "phoneNo": "9975720584",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.00804, 76.07011],
    "price": 4636,
    "email": "krushiuttpanabazarsamitituljapur612@example.com",
  },
  {
    "ownerName": "Agricultural Produce Market Committee Baramati",
    "name": "Agricultural Produce Market Committee Baramati",
    "_id": "6839526",
    "address": "Indapur Road, Market Yard",
    "city": "Pune",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "18-Jan-24",
    "registrationValidUpto": "17-Jan-29",
    "phoneNo": "9860305093",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.15174, 74.57767],
    "price": 4161,
    "email": "agriculturalproducemarketcommitteebaramati536@hotmail.com",
  },
  {
    "ownerName": "Agricultural Produce Market Committee Manchar",
    "name": "Agricultural Produce Market Committee Manchar",
    "_id": "6865174",
    "address": "Market yard Manchar,",
    "city": "Pune",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "19-Feb-24",
    "registrationValidUpto": "18-Feb-29",
    "phoneNo": "9922861133",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.00436, 73.94346],
    "price": 2271,
    "email": "agriculturalproducemarketcommitteemanchar24@example.com",
  },
  {
    "ownerName":
      "Agricultural Produce Market Committee Nandura Tq Nandura Dist Budhana",
    "name": "Agricultural Produce Market Committee Nandura",
    "_id": "6748172",
    "address": "TQ NANDURA, DIST BULDHANA",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "30-Jun-23",
    "registrationValidUpto": "29-Jun-28",
    "phoneNo": "9022118473",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.8372567, 76.4600208],
    "price": 2896,
    "email": "agriculturalproducemarketcommitteenandura960@hotmail.com",
  },
  {
    "ownerName": "Agricultural Produce Market Committee, Balapur",
    "name": "APMC Balapur",
    "_id": "6739981",
    "address": "Sub Yard Wadegaon, Balapur Patur Road",
    "city": "Akola",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "19-Jun-23",
    "registrationValidUpto": "18-Jun-28",
    "phoneNo": "9370543764",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.66612, 76.77386],
    "price": 3756,
    "email": "apmcbalapur771@example.com",
  },
  {
    "ownerName": "agriculture produce market committee,goregaon",
    "name": "APMC,Goregaon",
    "_id": "6687784",
    "address": "agriculture produce market committee,goregaon,",
    "city": "Gondiya",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "22-Feb-23",
    "registrationValidUpto": "21-Feb-28",
    "phoneNo": "7507277558",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.15483, 73.29147],
    "price": 3404,
    "email": "apmc,goregaon799@yahoo.com",
  },
  {
    "ownerName": "agriculture produce market committee,hinganghat.",
    "name": "Agriculture produce market committee, Hinganghat",
    "_id": "6852305",
    "address": "APMC, Hinganghat,",
    "city": "Wardha",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "06-Feb-24",
    "registrationValidUpto": "05-Feb-29",
    "phoneNo": "9860864627",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.54765, 78.84033],
    "price": 3812,
    "email": "agricultureproducemarketcommittee,hinganghat168@gmail.com",
  },
  {
    "ownerName": "APMC ,CHANDRAPUR",
    "name": "APMC,chandrapur",
    "_id": "6691299",
    "address": "APMC,datala road ,chandrapur,",
    "city": "Chandrapur",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "01-Mar-23",
    "registrationValidUpto": "28-Feb-28",
    "phoneNo": "9822711612",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.9426621, 79.8956424],
    "price": 4077,
    "email": "apmc,chandrapur800@hotmail.com",
  },
  {
    "ownerName": "APMC ,pauni",
    "name": "APMC Pauni",
    "_id": "6692289",
    "address": "Bhaitalawa ward Pauni, Pauni",
    "city": "Bhandara",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "06-Mar-23",
    "registrationValidUpto": "05-Mar-28",
    "phoneNo": "9881569891",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.79205, 79.63583],
    "price": 1052,
    "email": "apmcpauni686@yahoo.com",
  },
  {
    "ownerName": "APMC ,Tumsar",
    "name": "APMC ,tumsar",
    "_id": "6691562",
    "address": "agriculture produce market committee ,tumsar,",
    "city": "Bhandara",
    "state": "MAHARASHTRA",
    "capacity": "1147",
    "registrationDate": "03-Mar-23",
    "registrationValidUpto": "02-Mar-28",
    "phoneNo": "7666759424",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.38333, 79.73333],
    "price": 3233,
    "email": "apmc,tumsar459@gmail.com",
  },
  {
    "ownerName": "APMC LAsalgaon",
    "name": "APMC Lasalgaon",
    "_id": "6713887",
    "address": "Vinchur,",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "01-May-23",
    "registrationValidUpto": "30-Apr-28",
    "phoneNo": "7387670813",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.14384, 74.23836],
    "price": 1257,
    "email": "apmclasalgaon761@example.com",
  },
  {
    "ownerName": "APMC Malegaon",
    "name": "APMC Malegaon",
    "_id": "6763742",
    "address": "Main Market Yard Camp Road,",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "27-Jul-23",
    "registrationValidUpto": "26-Jul-28",
    "phoneNo": "7385572105",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5537, 74.52881],
    "price": 4724,
    "email": "apmcmalegaon29@hotmail.com",
  },
  {
    "ownerName": "APMC Shrigonda",
    "name": "APMC Shrigonda",
    "_id": "6861215",
    "address": "Market Yard Shrigonda, Duand-Jamkhed Road",
    "city": "Ahmadnagar",
    "state": "MAHARASHTRA",
    "capacity": "1000",
    "registrationDate": "14-Feb-24",
    "registrationValidUpto": "13-Feb-29",
    "phoneNo": "7028839989",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.61527, 74.69895],
    "price": 4005,
    "email": "apmcshrigonda418@yahoo.com",
  },

  {
    "ownerName": "Central Warehousing Corporation",
    "name": "CW Nanded ( Santosh Warehouse)",
    "_id": "5491647",
    "address": "Block No 178, Bhaygaon Road, Tuppa Nanded",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "24522",
    "registrationDate": "07-Jun-21",
    "registrationValidUpto": "06-Jun-26",
    "phoneNo": "9960420107",
    "status": "Inactive",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.16023, 77.31497],
    "price": 1011,
    "email": "cwnanded(santoshwarehouse)175@yahoo.com",
  },
  {
    "ownerName": "Central Warehousing Corporation",
    "name": "Kolhapur-II",
    "_id": "4131649",
    "address": "A-3,MIDC,Gokulshirgaon,Kolhapur,",
    "city": "Kolhapur",
    "state": "MAHARASHTRA",
    "capacity": "20000",
    "registrationDate": "31-Mar-21",
    "registrationValidUpto": "30-Mar-26",
    "phoneNo": "7767089708",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [16.6796885, 74.4681136],
    "price": 1003,
    "email": "kolhapur-ii434@hotmail.com",
  },
  {
    "ownerName": "Central Warehousing Corporation",
    "name": "CENTRAL WAREHOUSE, SANGLI",
    "_id": "6826564",
    "address": "3RD LANE, MARKET YARD, SANGLI",
    "city": "Sangli",
    "state": "MAHARASHTRA",
    "capacity": "16060",
    "registrationDate": "26-Dec-23",
    "registrationValidUpto": "25-Dec-28",
    "phoneNo": "9921508544",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [16.85438, 74.56417],
    "price": 1404,
    "email": "centralwarehouse,sangli372@yahoo.com",
  },
  {
    "ownerName": "Central Warehousing Corporation",
    "name": "Central Warehouse Amravati",
    "_id": "6869853",
    "address": "Krishna Nagar Post Office, New Cotton Market Road,Amravati",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "28920",
    "registrationDate": "22-Feb-24",
    "registrationValidUpto": "21-Feb-29",
    "phoneNo": "9158249847",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.93333, 77.75],
    "price": 3740,
    "email": "centralwarehouseamravati635@example.com",
  },
  {
    "ownerName": "Central Warehousing Corporation",
    "name": "CENTRAL WAREHOUSING CORPORATION WASHIM (PEG)",
    "_id": "5611640",
    "address":
      "C/o :- RABIA LOGISTICS PVT LTD, DAGAD UMRA FATA WASHIM-PUSAD ROAD",
    "city": "Washim",
    "state": "MAHARASHTRA",
    "capacity": "30000",
    "registrationDate": "18-Jun-21",
    "registrationValidUpto": "17-Jun-26",
    "phoneNo": "8999015267",
    "status": "Inactive",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.11152, 77.13221],
    "price": 4860,
    "email": "centralwarehousingcorporationwashim(peg)351@yahoo.com",
  },
  {
    "ownerName": "Central Warehousing Corporation",
    "name": "CENTRAL WAREHOUSE YAVATMAL",
    "_id": "6825665",
    "address": "DHAMANGAON ROAD, NEAR OCTROI CHECK POST",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "23714",
    "registrationDate": "26-Dec-23",
    "registrationValidUpto": "25-Dec-28",
    "phoneNo": "9372309019",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.15, 78.35],
    "price": 1961,
    "email": "centralwarehouseyavatmal698@outlook.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Daryapur",
    "_id": "6721625",
    "address": "Mauze-Banosa, Near ITI, Daryapur,",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "6000",
    "registrationDate": "26-May-23",
    "registrationValidUpto": "25-May-28",
    "phoneNo": "8805017485",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.9249, 77.32622],
    "price": 2254,
    "email": "maharashtra statewarehousingcorporation,daryapur437@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Risod",
    "_id": "6580054",
    "address": "APMC, Market Yard, Risod,",
    "city": "Washim",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9881751896",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.97549, 76.78844],
    "price": 4022,
    "email": "maharashtra statewarehousingcorporation,risod974@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Panvel (Multi Story)",
    "_id": "6586804",
    "address":
      "Maharashtra state Warehousing Corporation, Survey No. 437, Plot No. 465, Raigad Bazar, APMC Market Yard, Panvel",
    "city": "Raigarh",
    "state": "MAHARASHTRA",
    "capacity": "8100",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "8149199752",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.98878, 73.11013],
    "price": 2505,
    "email": "panvel(multistory)419@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "GANGAKHED",
    "_id": "6589147",
    "address": "PLOT NO.B-2, MIDC AREA,, GANGAKHED",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "7200",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9850611382",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.9130998, 76.7557068],
    "price": 4376,
    "email": "gangakhed992@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "NANDGAON",
    "_id": "6583744",
    "address": "APMC MARKET YARD, NANDGAON",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "1800",
    "registrationDate": "29-May-22",
    "registrationValidUpto": "28-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.3335523, 74.6707137],
    "price": 2771,
    "email": "nandgaon132@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Warora",
    "_id": "3851664",
    "address":
      "Maharashtra state warehousing Corporation Warora, Near Saraf Factory,Warora ,Dist-Chandrapur Pin-442907",
    "city": "Chandrapur",
    "state": "MAHARASHTRA",
    "capacity": "9880",
    "registrationDate": "25-Nov-19",
    "registrationValidUpto": "24-Nov-24",
    "phoneNo": "9405943202",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.23014, 79.00161],
    "price": 1579,
    "email": "mswcwarora785@outlook.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Tirthpuri",
    "_id": "6576813",
    "address": "MSWC, Tirthpuri, Taluka Ghansangavi,, Jalna -431209",
    "city": "Jalna",
    "state": "MAHARASHTRA",
    "capacity": "1580",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "7588957049",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.4396245, 75.9237956],
    "price": 2888,
    "email": "tirthpuri15@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Tumsar",
    "_id": "6579601",
    "address": "APMC, Market Yard, Tumsar",
    "city": "Bhandara",
    "state": "MAHARASHTRA",
    "capacity": "7956",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9158679823",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.7111225, 79.8641448],
    "price": 4147,
    "email": "tumsar607@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Godown Jalna",
    "_id": "6585814",
    "address":
      "Near Government godown, Near Bus Stand, Raut Nagar, Jalna -431203",
    "city": "Jalna",
    "state": "MAHARASHTRA",
    "capacity": "8850",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "8788294872",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.84102, 75.88636],
    "price": 1450,
    "email": "citygodownjalna294@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "KALWAN",
    "_id": "6578256",
    "address": "Market Yard, Kalwan, KALWAN",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "3500",
    "registrationDate": "24-May-22",
    "registrationValidUpto": "23-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5293817, 73.9521683],
    "price": 3894,
    "email": "kalwan775@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "UMARAGA",
    "_id": "6585186",
    "address": "EKONDI ROAD,, MARKET YARD",
    "city": "Osmanabad",
    "state": "MAHARASHTRA",
    "capacity": "3377",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9423326150",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.8406534, 76.5885554],
    "price": 1807,
    "email": "umaraga706@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "LASALGAON",
    "_id": "6582035",
    "address": "MARKET YARD, KOTAMGAON ROAD",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "4000",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.1426837, 74.2377507],
    "price": 1048,
    "email": "lasalgaon880@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC BARAMATI",
    "_id": "6577712",
    "address": "MIDC ,BARAMATI,",
    "city": "Pune",
    "state": "MAHARASHTRA",
    "capacity": "15819",
    "registrationDate": "24-May-22",
    "registrationValidUpto": "23-May-27",
    "phoneNo": "9158001058",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.15174, 74.57767],
    "price": 4341,
    "email": "mswcbaramati751@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Umarkhed",
    "_id": "6581136",
    "address": "Mahagaon Road, Umarkhed,",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "8280",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "7507550099",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.60144, 77.68878],
    "price": 2527,
    "email": "maharashtra statewarehousingcorporation,umarkhed88@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Malegaon (Washim)",
    "_id": "6635940",
    "address": "APMC, Near Rest House, Malegaon (Washim),",
    "city": "Washim",
    "state": "MAHARASHTRA",
    "capacity": "2850",
    "registrationDate": "26-Sep-22",
    "registrationValidUpto": "25-Sep-27",
    "phoneNo": "9970171187",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5537, 74.52881],
    "price": 1191,
    "email":
      "maharashtra statewarehousingcorporation,malegaon(washim)288@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Ahmednagar city",
    "_id": "6591754",
    "address": "WAKODI RAOD, BHAWANI NAGAR, MARKET YARD, AHMEDNAGAR,",
    "city": "Ahmadnagar",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "07-Jun-22",
    "registrationValidUpto": "06-Jun-27",
    "phoneNo": "9822347088",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.09457, 74.73843],
    "price": 3817,
    "email": "mswcahmednagarcity863@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC PANDHARPUR",
    "_id": "6579064",
    "address": "KORTI ROAD, IN FRONT OF KRUSHI OFFICE",
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "16424",
    "registrationDate": "25-May-22",
    "registrationValidUpto": "24-May-27",
    "phoneNo": "9158001342",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.67924, 75.33098],
    "price": 2184,
    "email": "mswcpandharpur935@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, OSMANABAD",
    "_id": "6591937",
    "address": "Marketyard, Near Tuljapur Naka, Osmanabad",
    "city": "Osmanabad",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "07-Jun-22",
    "registrationValidUpto": "06-Jun-27",
    "phoneNo": "8208543965",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.18158, 76.03889],
    "price": 1277,
    "email": "maharashtra statewarehousingcorporation,osmanabad680@gmail.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Warud",
    "_id": "6575641",
    "address": "Nagpur Road, Roshankhed Phata,",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "7650",
    "registrationDate": "19-May-22",
    "registrationValidUpto": "18-May-27",
    "phoneNo": "8149641881",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.47076, 78.26858],
    "price": 4362,
    "email": "maharashtra statewarehousingcorporation,warud647@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, PURNA",
    "_id": "6746820",
    "address": "NANDED-ROAD, PURNA",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "7510",
    "registrationDate": "27-Jun-23",
    "registrationValidUpto": "26-Jun-28",
    "phoneNo": "9850030618",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.1798, 77.02595],
    "price": 1373,
    "email": "maharashtra statewarehousingcorporation,purna96@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Indapur",
    "_id": "6586622",
    "address": "Marketyard APMC, Near hotel Khan Chacha",
    "city": "Pune",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9881697171",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.3, 73.25],
    "price": 3108,
    "email": "mswcindapur663@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "BODWAD",
    "_id": "6594543",
    "address": "APMC MARKET, MUKATINAGAR ROAD BODWAD",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.9034659, 76.0174431],
    "price": 4109,
    "email": "bodwad265@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Palghar",
    "_id": "6583835",
    "address":
      "Maharashtra state Warehousing Corporation, Nandore Naka, Near APMC, Manor Road",
    "city": "Thane",
    "state": "MAHARASHTRA",
    "capacity": "5000",
    "registrationDate": "29-May-22",
    "registrationValidUpto": "28-May-27",
    "phoneNo": "9029023752",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.684661, 72.8249112],
    "price": 3757,
    "email": "palghar176@hotmail.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "LONAND",
    "_id": "6596258",
    "address": "LONAND SATARA ROAD, KAPAD GAON, LONAND",
    "city": "Satara",
    "state": "MAHARASHTRA",
    "capacity": "20197",
    "registrationDate": "20-Jun-22",
    "registrationValidUpto": "19-Jun-27",
    "phoneNo": "9158001332",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.0387975, 74.186926],
    "price": 3337,
    "email": "lonand79@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Wani (Yavatmal)",
    "_id": "6635858",
    "address": "Chandrapur Road, Wani (Yavatmal),",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "8550",
    "registrationDate": "26-Sep-22",
    "registrationValidUpto": "25-Sep-27",
    "phoneNo": "9673527124",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.0639446, 78.9652282],
    "price": 1343,
    "email":
      "maharashtra statewarehousingcorporation,wani(yavatmal)315@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation , Hinganghat",
    "_id": "6667448",
    "address": "Nagpur Hydrabad Highway, Hinganghat",
    "city": "Wardha",
    "state": "MAHARASHTRA",
    "capacity": "6780",
    "registrationDate": "27-Dec-22",
    "registrationValidUpto": "26-Dec-27",
    "phoneNo": "9423619102",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.54765, 78.84033],
    "price": 2929,
    "email": "maharashtra statewarehousingcorporation,hinganghat712@yahoo.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "NAVAPUR",
    "_id": "6596704",
    "address": "APMC MARKET, Opp. Sai Mandi, Main Road, Navapur",
    "city": "Nandurbar",
    "state": "MAHARASHTRA",
    "capacity": "4000",
    "registrationDate": "22-Jun-22",
    "registrationValidUpto": "21-Jun-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.7904959, 72.6897825],
    "price": 1714,
    "email": "navapur58@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "JALNA BORKHEDI",
    "_id": "6586895",
    "address":
      "SHINDKHED RAJA ROAD, BORKHEDI DTST. JALNA, SHINDKHED RAJA ROAD, BORKHEDI DTST. JALNA",
    "city": "Jalna",
    "state": "MAHARASHTRA",
    "capacity": "33611",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9158001317",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.8900471, 75.9953284],
    "price": 2058,
    "email": "jalnaborkhedi29@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Nanded(MIDC)",
    "_id": "6589238",
    "address": "Plot No.B- 14-15 MIDC Area, Nanded",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "31209",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9158001335",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.16023, 77.31497],
    "price": 2422,
    "email": "mswcnanded(midc)722@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation",
    "_id": "6577175",
    "address":
      "Near Railway Station, Agriculture Markeing Produce Committe Katol",
    "city": "Nagpur",
    "state": "MAHARASHTRA",
    "capacity": "5850",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "7385785400",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.9329418, 77.7555379],
    "price": 4710,
    "email": "maharashtra statewarehousingcorporation545@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "NAMPUR",
    "_id": "6580864",
    "address": "APMC MARKET YARD, APMC",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.7266441, 74.3129666],
    "price": 2284,
    "email": "nampur378@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Malegaon",
    "_id": "6606065",
    "address": "CAMP ROAD, APMC MALEGAON, Malegaon",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "9600",
    "registrationDate": "22-Jul-22",
    "registrationValidUpto": "21-Jul-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5896873, 74.5717573],
    "price": 2563,
    "email": "malegaon61@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, JINTUR",
    "_id": "6612188",
    "address": "WARUD ROAD, JINTUR",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "5220",
    "registrationDate": "08-Aug-22",
    "registrationValidUpto": "07-Aug-27",
    "phoneNo": "9960851387",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.61186, 76.6874],
    "price": 2499,
    "email": "maharashtra statewarehousingcorporation,jintur980@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "YAWAL",
    "_id": "6600126",
    "address": "YAWAL APMC, YAWAL",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "4250",
    "registrationDate": "08-Jul-22",
    "registrationValidUpto": "07-Jul-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.2260018, 75.6950825],
    "price": 4374,
    "email": "yawal836@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, SAILU",
    "_id": "6578074",
    "address": "PATHRI ROAD, SAILU",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "7650",
    "registrationDate": "24-May-22",
    "registrationValidUpto": "23-May-27",
    "phoneNo": "9673191509",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.45513, 76.43946],
    "price": 2813,
    "email": "maharashtra statewarehousingcorporation,sailu133@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, JAWALA BAZAR",
    "_id": "6580591",
    "address": "APMC YARD, JAWALA BAZAR",
    "city": "Hingoli",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9028980032",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.5, 76.0],
    "price": 2215,
    "email": "maharashtra statewarehousingcorporation,jawalabazar673@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Majalgaon",
    "_id": "6594451",
    "address":
      "MSWC, Georai Road, Near Jining Presing, Post, PhulePimpalgaon, Majalgaon - 431131",
    "city": "Bid",
    "state": "MAHARASHTRA",
    "capacity": "12640",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "8007242826",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.15599, 76.21152],
    "price": 4377,
    "email": "mswcmajalgaon660@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Darwha",
    "_id": "6580146",
    "address": "Arni Road, Darwha,",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "8000",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9766578305",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.30862, 77.7691],
    "price": 3599,
    "email": "maharashtra statewarehousingcorporation,darwha912@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Hinganghat (APMC)",
    "_id": "6666721",
    "address": "Shivaji Market (APMC),, Hydrabad Highway, Hinganghat",
    "city": "Wardha",
    "state": "MAHARASHTRA",
    "capacity": "9920",
    "registrationDate": "26-Dec-22",
    "registrationValidUpto": "25-Dec-27",
    "phoneNo": "9423619102",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.54765, 78.84033],
    "price": 3824,
    "email":
      "maharashtra statewarehousingcorporation,hinganghat(apmc)511@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "PACHORA",
    "_id": "6667539",
    "address": "PACHORA APMC,",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "27-Dec-22",
    "registrationValidUpto": "26-Dec-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.6562575, 75.4011092],
    "price": 4107,
    "email": "pachora144@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, MANWAT",
    "_id": "6588784",
    "address": "NEAR GOVT. REST-HOUSE, MANWAT",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "13050",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9423958800",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.30133, 76.49735],
    "price": 4689,
    "email": "maharashtra statewarehousingcorporation,manwat8@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "OZAR",
    "_id": "6589774",
    "address": "Mumbai Agra Haighway,",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "8050",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.7054212, 75.3280592],
    "price": 1891,
    "email": "ozar740@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Khamgaon (Warkhed)",
    "_id": "6585632",
    "address": "Shegaon Road, Khamgaon (Warkhed),",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "29040",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9158001330",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.70738, 76.56827],
    "price": 1022,
    "email":
      "maharashtra statewarehousingcorporation,khamgaon(warkhed)685@gmail.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Chandur Bazar",
    "_id": "6579965",
    "address": "APMC, Market Yard, Chandur Bazar,",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "10800",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9527726322",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.2391, 77.74703],
    "price": 2228,
    "email": "maharashtra statewarehousingcorporation,chandurbazar416@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "CHALISGAON",
    "_id": "6599583",
    "address": "CHALISGAON APMC,",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "12800",
    "registrationDate": "05-Jul-22",
    "registrationValidUpto": "04-Jul-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5023656, 74.96557],
    "price": 3983,
    "email": "chalisgaon29@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, DEGLUR",
    "_id": "6756720",
    "address": "APMC MARKETYARD, BEHIND SHETKARI NIVAS, DEGLUR, Deglur",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "14-Jul-23",
    "registrationValidUpto": "13-Jul-28",
    "phoneNo": "9764669778",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.54829, 77.57695],
    "price": 2384,
    "email": "maharashtra statewarehousingcorporation,deglur998@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Malkapur",
    "_id": "6635585",
    "address": "Nandura Road, Malkapur,",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "6200",
    "registrationDate": "26-Sep-22",
    "registrationValidUpto": "25-Sep-27",
    "phoneNo": "9921472770",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.8856, 76.20371],
    "price": 3561,
    "email": "maharashtra statewarehousingcorporation,malkapur593@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Sillod",
    "_id": "6580419",
    "address":
      "MSWC, Aurangabad-Ajanta-Jalgaon Road, Sillod, Tal Sillod, Dist Aurangabad",
    "city": "Aurangabad",
    "state": "MAHARASHTRA",
    "capacity": "4740",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9850078978",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.30303, 75.65284],
    "price": 3971,
    "email": "mswcsillod567@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation",
    "_id": "6587612",
    "address": "Agriculture Produce Market Committee, Market Yard Savner",
    "city": "Nagpur",
    "state": "MAHARASHTRA",
    "capacity": "3150",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9764919922",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.9329418, 77.7555379],
    "price": 4770,
    "email": "maharashtra statewarehousingcorporation13@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Lasur ( Station",
    "_id": "6576276",
    "address": "MSWC, APMC Area, Lasur (station), Taluka- Gangapur, Aurangabad-",
    "city": "Aurangabad",
    "state": "MAHARASHTRA",
    "capacity": "4180",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "9860820981",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.9308686, 75.0127245],
    "price": 4870,
    "email": "lasur(station695@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Akola",
    "_id": "6593370",
    "address": "N-66, MIDC Area, Phase-4, Akola,",
    "city": "Akola",
    "state": "MAHARASHTRA",
    "capacity": "20000",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "9403047251",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5, 77.16667],
    "price": 3130,
    "email": "maharashtra statewarehousingcorporation,akola214@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Tasgaon",
    "_id": "6584460",
    "address": "Market Yard Tasgaon,",
    "city": "Sangli",
    "state": "MAHARASHTRA",
    "capacity": "3480",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9860345007",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [17.0904859, 74.6832675],
    "price": 3264,
    "email": "tasgaon377@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Karmala",
    "_id": "6581045",
    "address": '"Jamkhed Road, Karmala 413203", "M.S.W.C Market Yard,"',
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "8369278804",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.4077, 75.19386],
    "price": 2753,
    "email": "mswckarmala248@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "BEED",
    "_id": "6589592",
    "address": "PLOT NO.47,48, MIDC AREA BEED TQ.DIST.BEED",
    "city": "Bid",
    "state": "MAHARASHTRA",
    "capacity": "8726",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "8329768566",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.9918442, 75.909784],
    "price": 4818,
    "email": "beed402@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, DHARMABAD",
    "_id": "6582126",
    "address": "RATNALI ROAD,, DHARMABAD",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "8830758165",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.89116, 77.8494],
    "price": 3292,
    "email": "maharashtra statewarehousingcorporation,dharmabad647@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Hinganghat",
    "_id": "6633788",
    "address": "Nagpur Hydarabad Highway, Hinganghat",
    "city": "Wardha",
    "state": "MAHARASHTRA",
    "capacity": "19050",
    "registrationDate": "22-Sep-22",
    "registrationValidUpto": "21-Sep-27",
    "phoneNo": "9423619102",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.54765, 78.84033],
    "price": 2364,
    "email": "maharashtra statewarehousingcorporation,hinganghat509@example.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "JALGAON H-14",
    "_id": "6574925",
    "address": "PLOT NO.H14,MIDC AREA,JALGAON, JALGAON",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "61803",
    "registrationDate": "15-May-22",
    "registrationValidUpto": "14-May-27",
    "phoneNo": "9579713020",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.8455632, 75.1133537],
    "price": 4538,
    "email": "jalgaonh-1497@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation",
    "_id": "6580328",
    "address": "Agricultural Produce Market Committee, Gokul Nagar , Gadchiroli",
    "city": "Gadchiroli",
    "state": "MAHARASHTRA",
    "capacity": "4000",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "7875144303",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.9329418, 77.7555379],
    "price": 4873,
    "email": "maharashtra statewarehousingcorporation443@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC, AHMEDPUR",
    "_id": "6578975",
    "address": "MIDC Area, Nanded Road, AHMEDPUR",
    "city": "Latur",
    "state": "MAHARASHTRA",
    "capacity": "5100",
    "registrationDate": "25-May-22",
    "registrationValidUpto": "24-May-27",
    "phoneNo": "9975790190",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.70622, 76.93731],
    "price": 3268,
    "email": "mswc,ahmedpur434@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Jaysingpur",
    "_id": "6594279",
    "address": "Market yard,Near Pol Factory, Jaysingpur,",
    "city": "Kolhapur",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "9175927336",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [16.7789886, 74.5564244],
    "price": 4331,
    "email": "jaysingpur321@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "NANDURBAR",
    "_id": "6592208",
    "address": "G.T.P.college Road Nandurbar, Opp Shani mandir, Nandurbar",
    "city": "Nandurbar",
    "state": "MAHARASHTRA",
    "capacity": "11520",
    "registrationDate": "07-Jun-22",
    "registrationValidUpto": "06-Jun-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.5141622, 74.5405513],
    "price": 1127,
    "email": "nandurbar543@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Sangola",
    "_id": "3831646",
    "address": "APMC ,Market Yard,",
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "2980",
    "registrationDate": "25-Nov-19",
    "registrationValidUpto": "24-Nov-24",
    "phoneNo": "9420662254",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.43948, 75.19379],
    "price": 1584,
    "email": "mswcsangola23@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Ichalkaranji",
    "_id": "6583025",
    "address":
      "Market Yard Sangli Road Ichalkaranji, Market Yard Sangli Road Ichalkaranji",
    "city": "Kolhapur",
    "state": "MAHARASHTRA",
    "capacity": "3000",
    "registrationDate": "29-May-22",
    "registrationValidUpto": "28-May-27",
    "phoneNo": "9175927336",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [16.6959348, 74.4555755],
    "price": 2951,
    "email": "ichalkaranji223@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Khamgaon city",
    "_id": "6635767",
    "address": "APMC, Market Yard, Khamgaon,",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "3620",
    "registrationDate": "26-Sep-22",
    "registrationValidUpto": "25-Sep-27",
    "phoneNo": "8855899877",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.70738, 76.56827],
    "price": 2454,
    "email": "maharashtra statewarehousingcorporation,khamgaoncity428@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "AMBAD (NASHIK)",
    "_id": "6612451",
    "address": "H-105 MIDC, AMBAD NASHIK",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "2880",
    "registrationDate": "08-Aug-22",
    "registrationValidUpto": "07-Aug-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.9499946, 73.7431463],
    "price": 4490,
    "email": "ambad(nashik)929@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corpration, Arvi",
    "_id": "6594360",
    "address": "Pulgaon Road, Arvi,",
    "city": "Wardha",
    "state": "MAHARASHTRA",
    "capacity": "9000",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "9420246333",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.99645, 78.22868],
    "price": 1520,
    "email": "maharashtra statewarehousingcorpration,arvi531@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MANMAD",
    "_id": "6579874",
    "address": "APMC MARKET YARD, CHANWAD ROAD MANMAD",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "12900",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.2519828, 74.4392286],
    "price": 3448,
    "email": "manmad749@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Wai",
    "_id": "4211654",
    "address": "Plot no-B 50, Near Garware Company ,MIDC Wai",
    "city": "Satara",
    "state": "MAHARASHTRA",
    "capacity": "7600",
    "registrationDate": "11-Dec-19",
    "registrationValidUpto": "10-Dec-24",
    "phoneNo": "9860345007",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.95276, 73.89058],
    "price": 4531,
    "email": "mswcwai538@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Phaltan",
    "_id": "6586986",
    "address": "At Tambmal, Lonand - Phaltan Road, Post Farandwadi, Tal. Phalan",
    "city": "Satara",
    "state": "MAHARASHTRA",
    "capacity": "8920",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "8830845445",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.9579342, 74.4142354],
    "price": 2901,
    "email": "phaltan316@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "LOHARA (Y)",
    "_id": "6579247",
    "address": "MIDC Area, Lohara,",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "16364",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "9665234365",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.3933075, 78.4268689],
    "price": 1705,
    "email": "lohara(y)830@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC RATNAGIRI",
    "_id": "6578348",
    "address": "T-6 MIDC ,MIRJOLE BLOCK,, TAL & DIST. RATNAGIRI",
    "city": "Ratnagiri",
    "state": "MAHARASHTRA",
    "capacity": "14260",
    "registrationDate": "24-May-22",
    "registrationValidUpto": "23-May-27",
    "phoneNo": "8097537118",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.0, 73.5],
    "price": 4147,
    "email": "mswcratnagiri76@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "AKKALKOT",
    "_id": "6593552",
    "address": "Akkalkot, Akkalkot",
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "7704",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "9175989021",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.515193, 76.212278],
    "price": 1203,
    "email": "akkalkot144@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "SHAHADA",
    "_id": "6581672",
    "address": "BEHIND State BANK, MARKET YARD",
    "city": "Nandurbar",
    "state": "MAHARASHTRA",
    "capacity": "5100",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.740052, 78.635796],
    "price": 4390,
    "email": "shahada210@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Lote Parshuram",
    "_id": "6769053",
    "address": "M.I.D.C Area lote (P) P.29,",
    "city": "Ratnagiri",
    "state": "MAHARASHTRA",
    "capacity": "5830",
    "registrationDate": "31-Jul-23",
    "registrationValidUpto": "30-Jul-28",
    "phoneNo": "8097537118",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.58437, 73.4979351],
    "price": 4516,
    "email": "loteparshuram470@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Vaijapur",
    "_id": "6746556",
    "address": "MSWC, Opp power house,, Aurangabad Rd, Vaijapur",
    "city": "Aurangabad",
    "state": "MAHARASHTRA",
    "capacity": "6320",
    "registrationDate": "27-Jun-23",
    "registrationValidUpto": "26-Jun-28",
    "phoneNo": "9860820981",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.92672, 74.7275],
    "price": 2774,
    "email": "mswcvaijapur785@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, AUSA",
    "_id": "6746911",
    "address": "PLOT NO.B-11 MIDCI AUSA, AUSA",
    "city": "Latur",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "27-Jun-23",
    "registrationValidUpto": "26-Jun-28",
    "phoneNo": "9579866338",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.24728, 76.4993],
    "price": 1964,
    "email": "maharashtra statewarehousingcorporation,ausa975@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra State WAREHOUSING CORPORATION, PARBHANI-CITY",
    "_id": "6589501",
    "address": "Behind Zilha Parishad Parbhani, Near DSM Collage, PARBHANI",
    "city": "Parbhani",
    "state": "MAHARASHTRA",
    "capacity": "6000",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9545011693",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.5, 76.75],
    "price": 1274,
    "email":
      "maharashtra statewarehousingcorporation,parbhani-city809@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "UDGIRMSWC,A1MIDC Area, Loni,Nanded Road,Udgir",
    "_id": "6630818",
    "address": "MSWC,A1MIDC Area, Loni,Nanded Road,Udgir, UDGIR",
    "city": "Latur",
    "state": "MAHARASHTRA",
    "capacity": "12300",
    "registrationDate": "19-Sep-22",
    "registrationValidUpto": "18-Sep-27",
    "phoneNo": "9970640322",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.39258, 77.11756],
    "price": 1851,
    "email": "udgirmswc,a1midcarea,loni,nandedroad,udgir537@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "KASODA",
    "_id": "6598593",
    "address": "APMC MARKET YARD, KASODA",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "30-Jun-22",
    "registrationValidUpto": "29-Jun-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.8211306, 75.2956366],
    "price": 2234,
    "email": "kasoda982@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Karjat",
    "_id": "6589329",
    "address":
      "Maharashtra state Warehousing Corporation, Dahivali Krushi Utpanna Bazar Samiti, Market Yard",
    "city": "Raigarh",
    "state": "MAHARASHTRA",
    "capacity": "1450",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9137308234",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.9107, 73.32354],
    "price": 4417,
    "email": "mswckarjat558@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, NANDED-city",
    "_id": "6634505",
    "address": "NANDED-HINGOLI ROAD, VASANT NAGER",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "5640",
    "registrationDate": "23-Sep-22",
    "registrationValidUpto": "22-Sep-27",
    "phoneNo": "9823426019",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.16023, 77.31497],
    "price": 3793,
    "email": "maharashtra statewarehousingcorporation,nanded-city960@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Pusad",
    "_id": "6633606",
    "address": "Dhankeshwar Road, Washim Road,",
    "city": "Yavatmal",
    "state": "MAHARASHTRA",
    "capacity": "8000",
    "registrationDate": "22-Sep-22",
    "registrationValidUpto": "21-Sep-27",
    "phoneNo": "9767960097",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.9089, 77.56825],
    "price": 1732,
    "email": "maharashtra statewarehousingcorporation,pusad248@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Telhara",
    "_id": "6576722",
    "address": "APMC, Market Yar, Telhara,",
    "city": "Akola",
    "state": "MAHARASHTRA",
    "capacity": "4800",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "8788101807",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.02694, 76.83889],
    "price": 4634,
    "email": "maharashtra statewarehousingcorporation,telhara5@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MSWC Solapur",
    "_id": "6593735",
    "address": "PLOT NO.8, SIDDHESHWAR MARKET YARD,",
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "5400",
    "registrationDate": "13-Jun-22",
    "registrationValidUpto": "12-Jun-27",
    "phoneNo": "9960243003",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [17.75, 75.5],
    "price": 4388,
    "email": "mswcsolapur796@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Achalpur",
    "_id": "6633960",
    "address": "APMC, Market Yard, Achalpur,",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "5000",
    "registrationDate": "22-Sep-22",
    "registrationValidUpto": "21-Sep-27",
    "phoneNo": "9604743185",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.25722, 77.50861],
    "price": 1285,
    "email": "maharashtra statewarehousingcorporation,achalpur492@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Akot",
    "_id": "6581581",
    "address": "APMC, Market Yard, Akot,",
    "city": "Akola",
    "state": "MAHARASHTRA",
    "capacity": "3870",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "9146938353",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.09639, 77.05861],
    "price": 4779,
    "email": "maharashtra statewarehousingcorporation,akot890@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Nandgaon Kh.",
    "_id": "6582217",
    "address": "APMC, Market Yard, Amravati Road, Nadgaon Khandeshwar,",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "3600",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "8208231129",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.5964, 78.2077],
    "price": 2101,
    "email": "maharashtra statewarehousingcorporation,nandgaonkh.90@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Mehekar",
    "_id": "6589055",
    "address": "APMC, Market Yard, Dongaon Road, Mehekar,",
    "city": "Buldana",
    "state": "MAHARASHTRA",
    "capacity": "10000",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9881751896",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [20.1505, 76.56841],
    "price": 3819,
    "email": "maharashtra statewarehousingcorporation,mehekar425@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, KINWAT",
    "_id": "6589956",
    "address":
      "Mahur Rd., Co. Op. Cotton Ginning & Pressing Soc. Ltd. Kinwat, Tq. Kinwat, KINWAT",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "3150",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "7972962388",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.62368, 78.2],
    "price": 3940,
    "email": "maharashtra statewarehousingcorporation,kinwat513@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MIRAJ",
    "_id": "6587521",
    "address":
      "Miraj Pandharpur road, Tasgaon Phata, Miraj, Gat No. 2233A, Malgaon,Miraj",
    "city": "Sangli",
    "state": "MAHARASHTRA",
    "capacity": "14400",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9404716517",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [16.858516, 74.7108947],
    "price": 2095,
    "email": "miraj763@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Takari",
    "_id": "6586713",
    "address": "Marketyard, Takari, Tal- Walwa,,",
    "city": "Sangli",
    "state": "MAHARASHTRA",
    "capacity": "2980",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9096978970",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.4831623, 80.3577061],
    "price": 3423,
    "email": "takari297@hotmail.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "RAVER",
    "_id": "6582308",
    "address": "Near by ITI,Utkheda Road,Pal Phata, RAVER",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "5160",
    "registrationDate": "28-May-22",
    "registrationValidUpto": "27-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.2268818, 75.9985933],
    "price": 1660,
    "email": "raver955@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "DHARANGAON",
    "_id": "6599047",
    "address": "A.P.M.C MARKET, DHARANGAON",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "6600",
    "registrationDate": "01-Jul-22",
    "registrationValidUpto": "30-Jun-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.0283404, 75.367342],
    "price": 4721,
    "email": "dharangaon949@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "CHOPDA",
    "_id": "6580500",
    "address": "APMC MARKET YARD, CHOPADA",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "4050",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.2771494, 75.3402197],
    "price": 1038,
    "email": "chopda136@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "WANI NASHIK",
    "_id": "6599674",
    "address": "MULANE ROAD,WANI (N), WANI",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "05-Jul-22",
    "registrationValidUpto": "04-Jul-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.99727, 73.79096],
    "price": 4209,
    "email": "waninashik617@yahoo.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "DHAMANGAON",
    "_id": "6579429",
    "address": "Near by DSMS Colloge, Dhamangaon, Dhamangaon",
    "city": "Amravati",
    "state": "MAHARASHTRA",
    "capacity": "12043",
    "registrationDate": "26-May-22",
    "registrationValidUpto": "25-May-27",
    "phoneNo": "8805060702",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [21.1773882, 76.2180723],
    "price": 3599,
    "email": "dhamangaon408@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Partur",
    "_id": "6576995",
    "address":
      "MSWC, APMC Area, Pardgaon Road, Near Railway Track, Tal.Partur, Jalna 431501",
    "city": "Jalna",
    "state": "MAHARASHTRA",
    "capacity": "5840",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "7588089986",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.4882762, 76.2606978],
    "price": 4698,
    "email": "partur331@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "KHADKI AHMADNAGAR",
    "_id": "6576904",
    "address": '"At Khadki, Post-Khandala,, Tal-Nagar, Dist-Ahmednagar "',
    "city": "Ahmadnagar",
    "state": "MAHARASHTRA",
    "capacity": "8944",
    "registrationDate": "23-May-22",
    "registrationValidUpto": "22-May-27",
    "phoneNo": "9822148684",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [18.9589029, 74.7043477],
    "price": 1748,
    "email": "khadkiahmadnagar313@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state Warehousing Corporation, Washim",
    "_id": "6575823",
    "address": "APMN, Market Yard, Near Railway Station, Washim,",
    "city": "Washim",
    "state": "MAHARASHTRA",
    "capacity": "10950",
    "registrationDate": "19-May-22",
    "registrationValidUpto": "18-May-27",
    "phoneNo": "9765439919",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [20.11152, 77.13221],
    "price": 1154,
    "email": "maharashtra statewarehousingcorporation,washim20@outlook.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "KUDAL",
    "_id": "6588966",
    "address": "Kudal, Kudal",
    "city": "Sindhudurg",
    "state": "MAHARASHTRA",
    "capacity": "9821",
    "registrationDate": "01-Jun-22",
    "registrationValidUpto": "31-May-27",
    "phoneNo": "9403322939",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [16.0635268, 73.8392416],
    "price": 3929,
    "email": "kudal401@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "NAGAPUR AHMEDNAGAR",
    "_id": "6575914",
    "address": "P 153 NAGAPUR MIDC, AHMEDNAGAR, NEAR JIMKHANA",
    "city": "Ahmadnagar",
    "state": "MAHARASHTRA",
    "capacity": "22854",
    "registrationDate": "19-May-22",
    "registrationValidUpto": "18-May-27",
    "phoneNo": "9822858423",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.4659044, 74.9901867],
    "price": 3505,
    "email": "nagapurahmednagar329@outlook.com",
  },

  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Parli Tokwadi",
    "_id": "6575013",
    "address": "PARLI BEED ROAD, TOKWADI",
    "city": "Bid",
    "state": "MAHARASHTRA",
    "capacity": "15378",
    "registrationDate": "15-May-22",
    "registrationValidUpto": "14-May-27",
    "phoneNo": "9763816355",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [18.8718947, 76.5013432],
    "price": 3335,
    "email": "parlitokwadi494@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Ashti",
    "_id": "6584643",
    "address":
      "MSWC, APMC Area ( Dhotar Joda), Taluka Partur, Partur, Jalna - 431507",
    "city": "Jalna",
    "state": "MAHARASHTRA",
    "capacity": "2000",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "7588957049",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.2056584, 78.1827905],
    "price": 2167,
    "email": "ashti337@example.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "JALGAON B-6",
    "_id": "6584916",
    "address": "AJANTHA ROAD, MIDC B-6 JALGAON",
    "city": "Jalgaon",
    "state": "MAHARASHTRA",
    "capacity": "16600",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.042262, 76.533479],
    "price": 4261,
    "email": "jalgaonb-6688@hotmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "MUSALGAON (NASHIK)",
    "_id": "6614887",
    "address": "Plot No. 142/2,, MUSALGAON MIDC MUSALGAON",
    "city": "Nashik",
    "state": "MAHARASHTRA",
    "capacity": "3000",
    "registrationDate": "13-Aug-22",
    "registrationValidUpto": "12-Aug-27",
    "phoneNo": "8408882562",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [19.8346768, 74.0535946],
    "price": 2068,
    "email": "musalgaon(nashik)927@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "CHINCHOLI (MIDC)",
    "_id": "6584825",
    "address": "B/10 CHINCHOLI MIDC,",
    "city": "Solapur",
    "state": "MAHARASHTRA",
    "capacity": "21905",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9158008754",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [17.46483, 77.41895],
    "price": 1221,
    "email": "chincholi(midc)270@gmail.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Maharashtra state WAREHOUSING CORPORATION, WAI BAZAR",
    "_id": "6584734",
    "address": "Mahur Kinwat Rd., APMC Market Yard Wai Bazar,, WAI BAZAR",
    "city": "Nanded",
    "state": "MAHARASHTRA",
    "capacity": "3150",
    "registrationDate": "30-May-22",
    "registrationValidUpto": "29-May-27",
    "phoneNo": "9960440933",
    "status": "Active",
    "type": "hot",
    "image": "/images/warehouse_1.jpg",
    "location": [21.5945, 77.1261],
    "price": 4861,
    "email": "maharashtra statewarehousingcorporation,waibazar464@yahoo.com",
  },
  {
    "ownerName": "Maharashtra state Warehousing Corporation",
    "name": "Georai",
    "_id": "6596977",
    "address": "MSWC, APMC Area,, Beed Road, Georai , Beed- 431127",
    "city": "Bid",
    "state": "MAHARASHTRA",
    "capacity": "6820",
    "registrationDate": "23-Jun-22",
    "registrationValidUpto": "22-Jun-27",
    "phoneNo": "8788575878",
    "status": "Active",
    "type": "cold",
    "image": "/images/warehouse_1.jpg",
    "location": [19.2625294, 75.7504928],
    "price": 3108,
    "email": "georai615@example.com",
  },
]

# Function to generate a random username
def generate_username():
    return ''.join(random.choices(string.ascii_lowercase, k=8))

# Function to randomly select crops
def select_random_crops(num_crops):
    return random.sample(crops_array, num_crops)

# Modify each object in the array
for warehouse in warehouseDetailData:
    # Remove the '_id' parameter if it exists
    if '_id' in warehouse:
        del warehouse['_id']
    # Change the 'type' field to an array type containing the original value
    warehouse['type'] = [warehouse['type']]
    # Add 'username' and 'password' fields
    warehouse['username'] = generate_username()
    warehouse['password'] = "Bangalore"

    # Convert capacity to an integer
    capacity = int(warehouse['capacity'])
    # Calculate the maximum value for 'occupied' based on 40% of 'capacity'
    max_occupied = int(capacity * 0.4)
    # Generate a random value for 'occupied' that is less than or equal to max_occupied, then convert to string
    warehouse['occupied'] = str(random.randint(0, max_occupied))

    # Determine the number of crops based on capacity (3 to 5)
    num_crops = random.randint(3, 5) if capacity > 0 else 0
    # Select random crops
    warehouse['typeOfCrop'] = select_random_crops(num_crops)

# Write the modified data back to the JavaScript file
with open('warehouse_details.js', 'w') as file:
    file.write("const warehouseDetailData = " + json.dumps(warehouseDetailData, indent=4) + ";")

# Count the number of warehouses processed
count = len(warehouseDetailData)
print(f"Number of warehouses processed: {count}")