const warehouseDetails = [
  {
    ownerName: "A.P.M.C.MALKAPUR",
    name: "APMC MALKAPUR",
    _id: "6751143",
    Address: "BELAD YARD ,MALKAPUR,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "04-Jul-23",
    "Registration Valid Upto": "03-Jul-28",
    phoneNo: "9960783901",
    Status: "Active",
    type: "hot",
    location: [17.2746815,74.1886849],
  },
  {
    ownerName: "AAI SHARDA LOGISTICS PRIVATE LIMITED",
    name: "AAI SHARDA LOGISTICS PRIVATE LIMITED",
    _id: "6744759",
    Address: "At Gut No. 68/2/B, 68/3/A, 67/1/B1, Village - Hol T Haveli,",
    city: "Nandurbar",
    state: "MAHARASHTRA",
    capacity: "20000",
    "Registration Date": "24-Jun-23",
    "Registration Valid Upto": "23-Dec-27",
    phoneNo: "9850070254",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Abhimanyu Gujar",
    name: "GANRAJ KRUPA WARE HOUSING COMPANY",
    _id: "6608319",
    Address:
      "Opp,Karad Railway Good Shed, Karad Railway station, Oglewadi, Tal:- Karad Dist:- Satara",
    city: "Satara",
    state: "MAHARASHTRA",
    capacity: "4000",
    "Registration Date": "29-Jul-22",
    "Registration Valid Upto": "28-Jul-27",
    phoneNo: "9822245555",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "AGRICULTURAL PRODUCE MARKET COMMITTEE",
    name: "KRUSHI UTTPANA BAZAR SAMITI TULJAPUR",
    _id: "6763296",
    Address: "Latur road Market yard,",
    city: "Osmanabad",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "27-Jul-23",
    "Registration Valid Upto": "26-Jul-28",
    phoneNo: "9975720584",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "Agricultural Produce Market Committee Baramati",
    name: "Agricultural Produce Market Committee Baramati",
    _id: "6839526",
    Address: "Indapur Road, Market Yard",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "18-Jan-24",
    "Registration Valid Upto": "17-Jan-29",
    phoneNo: "9860305093",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Agricultural Produce Market Committee Barshi",
    name: "Agricultural Produce Committee Barshi",
    _id: "6749162",
    Address: "Tuljapur Road, Market yard",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "30-Jun-23",
    "Registration Valid Upto": "29-Jun-28",
    phoneNo: "8888526933",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Agricultural Produce Market Committee Kurduvadi",
    name: "Agricultural Produce Market Committee Kurduwadi",
    _id: "6840060",
    Address: "APMC Kurduwadi Market yard, Tembhurni Road",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "18-Jan-24",
    "Registration Valid Upto": "17-Jan-29",
    phoneNo: "9284915656",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Agricultural Produce Market Committee Manchar",
    name: "Agricultural Produce Market Committee Manchar",
    _id: "6865174",
    Address: "Market yard Manchar,",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "19-Feb-24",
    "Registration Valid Upto": "18-Feb-29",
    phoneNo: "9922861133",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName:
      "Agricultural Produce Market Committee Nandura Tq Nandura Dist Budhana",
    name: "Agricultural Produce Market Committee Nandura",
    _id: "6748172",
    Address: "TQ NANDURA, DIST BULDHANA",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "30-Jun-23",
    "Registration Valid Upto": "29-Jun-28",
    phoneNo: "9022118473",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Agricultural Produce Market Committee, Balapur",
    name: "APMC Balapur",
    _id: "6739981",
    Address: "Sub Yard Wadegaon, Balapur Patur Road",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "19-Jun-23",
    "Registration Valid Upto": "18-Jun-28",
    phoneNo: "9370543764",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "Agriculture Produce Market Comm.",
    name: "A.P.M.C. Digras Warehouse",
    _id: "6756092",
    Address: "Digras APMC Market Yard, Shivaji Chowk",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "1",
    "Registration Date": "14-Jul-23",
    "Registration Valid Upto": "13-Jul-28",
    phoneNo: "9422167294",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "agriculture produce market commitee,gondpimpri",
    name: "APMC,gondpimpri",
    _id: "6717847",
    Address: "apmc,gondpimpri,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "19-May-23",
    "Registration Valid Upto": "18-May-28",
    phoneNo: "8830079725",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "agriculture produce market committee, bhrmpuri",
    name: "APMC, bramhpuri",
    _id: "6706147",
    Address: "APMC, bramhpuri,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "31-Mar-23",
    "Registration Valid Upto": "30-Mar-28",
    phoneNo: "8329884348",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "agriculture produce market committee,amgaon",
    name: "APMC ,Amgaon",
    _id: "6690127",
    Address: "agriculture produce market committee,amgaon,",
    city: "Gondiya",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "28-Feb-23",
    "Registration Valid Upto": "27-Feb-28",
    phoneNo: "9022500541",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "agriculture produce market committee,goregaon",
    name: "APMC,Goregaon",
    _id: "6687784",
    Address: "agriculture produce market committee,goregaon,",
    city: "Gondiya",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "22-Feb-23",
    "Registration Valid Upto": "21-Feb-28",
    phoneNo: "7507277558",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "agriculture produce market committee,hinganghat.",
    name: "Agriculture produce market committee, Hinganghat",
    _id: "6852305",
    Address: "APMC, Hinganghat,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "06-Feb-24",
    "Registration Valid Upto": "05-Feb-29",
    phoneNo: "9860864627",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "Agriculture produce market committee,parshiwani.",
    name: "APMC Parshiwani",
    _id: "6825848",
    Address: "agriculture market committee, parshiwani,",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "26-Dec-23",
    "Registration Valid Upto": "25-Dec-28",
    phoneNo: "8770467546",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "agriculture produce market committee,sindewahi",
    name: "agriculture produce market committee,sindewahi",
    _id: "6699482",
    Address: "apmc,sub market yard ,navargaon,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "27-Mar-23",
    "Registration Valid Upto": "26-Mar-28",
    phoneNo: "9284858140",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "agriculture,produce market commitee,chimur",
    name: "APMC ,CHIMUR",
    _id: "6691745",
    Address: "APMC ,CHIMUR,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "03-Mar-23",
    "Registration Valid Upto": "02-Mar-28",
    phoneNo: "9545310259",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "amogh agrotech",
    name: "AMOGH AGROTECH",
    _id: "8651642",
    Address: "1670 TASGAON MANERAJURI ROAD,",
    city: "Sangli",
    state: "MAHARASHTRA",
    capacity: "1707",
    "Registration Date": "14-Aug-20",
    "Registration Valid Upto": "13-Aug-25",
    phoneNo: "9923302846",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "ANDURA AGRO PRODUCER COMPANY LIMITED",
    name: "ANDURA AGRO PRODUCER COMPANY LIMITED",
    _id: "6795157",
    Address: "C-21,RUGVED,SUDHIR COLONY, NEAR HANUMAN MANDIR",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "750",
    "Registration Date": "27-Oct-23",
    "Registration Valid Upto": "26-Apr-25",
    phoneNo: "9689350197",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC ,CHANDRAPUR",
    name: "APMC,chandrapur",
    _id: "6691299",
    Address: "APMC,datala road ,chandrapur,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "01-Mar-23",
    "Registration Valid Upto": "28-Feb-28",
    phoneNo: "9822711612",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC ,lakhani",
    name: "APMC ,lakhani",
    _id: "6688238",
    Address: "agriculture produce market commitee,lakhani,",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "23-Feb-23",
    "Registration Valid Upto": "22-Feb-28",
    phoneNo: "9404523726",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC ,pauni",
    name: "APMC Pauni",
    _id: "6692289",
    Address: "Bhaitalawa ward Pauni, Pauni",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "06-Mar-23",
    "Registration Valid Upto": "05-Mar-28",
    phoneNo: "9881569891",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC ,pombhurna",
    name: "agriculture produce market committee,pombhurna",
    _id: "6689400",
    Address: "apmc,pombhurna,aksapur road,pombhurna,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "27-Feb-23",
    "Registration Valid Upto": "26-Feb-28",
    phoneNo: "9579083332",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC ,SINDI",
    name: "APMC SELOO",
    _id: "6693360",
    Address: "SUKLI STATION ROAD,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "07-Mar-23",
    "Registration Valid Upto": "06-Mar-28",
    phoneNo: "9970356620",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC ,SINDI",
    name: "APMC submarket, seloo",
    _id: "6827737",
    Address: "sukli station road ,seloo,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "26-Dec-23",
    "Registration Valid Upto": "25-Dec-28",
    phoneNo: "9970356620",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC ,Tumsar",
    name: "APMC ,tumsar",
    _id: "6691562",
    Address: "agriculture produce market committee ,tumsar,",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "03-Mar-23",
    "Registration Valid Upto": "02-Mar-28",
    phoneNo: "7666759424",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC ,varora",
    name: "apmc, varora",
    _id: "6694715",
    Address: "apmc, sub market yard mandheli,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "14-Mar-23",
    "Registration Valid Upto": "13-Mar-28",
    phoneNo: "9764063688",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Armori",
    name: "APMC Armori",
    _id: "6680318",
    Address: "Agriculture market Committee,sub market yard kurkheda,",
    city: "Gadchiroli",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "06-Feb-23",
    "Registration Valid Upto": "05-Feb-28",
    phoneNo: "9404817890",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC BARSHITAKLI",
    name: "A.p.m.c. barashitakli",
    _id: "6759872",
    Address: "Apmc barshi takli mahan road near railway station barshi takli.,",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "20-Jul-23",
    "Registration Valid Upto": "19-Jul-28",
    phoneNo: "919766677",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC Bhiwapur",
    name: "APMC Bhiwapur",
    _id: "6699300",
    Address: "at post bhiwapur ta bhiwapur, nakshi road",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "27-Mar-23",
    "Registration Valid Upto": "26-Mar-28",
    phoneNo: "9422220104",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC korpana",
    name: "APMC Korpana",
    _id: "6700652",
    Address: "APMC korpana TQ.Korpana,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "28-Mar-23",
    "Registration Valid Upto": "27-Mar-28",
    phoneNo: "9890328102",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Lakhandur",
    name: "APMC,lakhandur",
    _id: "6689319",
    Address: "APMC, lakhandur,",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "27-Feb-23",
    "Registration Valid Upto": "26-Feb-28",
    phoneNo: "9423761332",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC LAsalgaon",
    name: "APMC Lasalgaon",
    _id: "6713887",
    Address: "Vinchur,",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "01-May-23",
    "Registration Valid Upto": "30-Apr-28",
    phoneNo: "7387670813",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Malegaon",
    name: "APMC Malegaon",
    _id: "6763742",
    Address: "Main Market Yard Camp Road,",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "27-Jul-23",
    "Registration Valid Upto": "26-Jul-28",
    phoneNo: "7385572105",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Pulgaon",
    name: "APMC pulgaov sub market yard Devali",
    _id: "6694350",
    Address: "Devali TQ.Devali,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "14-Mar-23",
    "Registration Valid Upto": "13-Mar-28",
    phoneNo: "9850412844",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC SAVALI",
    name: "APMC, sawali",
    _id: "6705511",
    Address: "APMC, sawali,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "31-Mar-23",
    "Registration Valid Upto": "30-Mar-28",
    phoneNo: "9422838111",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Shrigonda",
    name: "APMC Shrigonda",
    _id: "6861215",
    Address: "Market Yard Shrigonda, Duand-Jamkhed Road",
    city: "Ahmadnagar",
    state: "MAHARASHTRA",
    capacity: "1000",
    "Registration Date": "14-Feb-24",
    "Registration Valid Upto": "13-Feb-29",
    phoneNo: "7028839989",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC Sironcha",
    name: "APMC, sironcha",
    _id: "6709836",
    Address: "APMC ,sironcha,",
    city: "Gadchiroli",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "17-Apr-23",
    "Registration Valid Upto": "16-Apr-28",
    phoneNo: "7588302009",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC Umared",
    name: "APMC Umared Warehouse",
    _id: "6681399",
    Address: "AT Apmc Umared sub market yard champa nagpur umared road,",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "1146",
    "Registration Date": "11-Feb-23",
    "Registration Valid Upto": "10-Feb-28",
    phoneNo: "9921304211",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC Yeola",
    name: "submarket Patoda ( APMC Yeola)",
    _id: "6748800",
    Address: "SUb Market yard, Yeola Road",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1170",
    "Registration Date": "30-Jun-23",
    "Registration Valid Upto": "29-Jun-28",
    phoneNo: "9423478313",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC, aheri",
    name: "APMC aheri",
    _id: "6701288",
    Address: "APMC aheri,aheri,",
    city: "Gadchiroli",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "28-Mar-23",
    "Registration Valid Upto": "27-Mar-28",
    phoneNo: "7499836960",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC, arjuni morgaon",
    name: "APMC,arjuni morgaon",
    _id: "6704704",
    Address: "APMC, arjuni morgaon,",
    city: "Gondiya",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "31-Mar-23",
    "Registration Valid Upto": "30-Mar-28",
    phoneNo: "7066502088",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "APMC, mandhal",
    name: "APMC Mandhal",
    _id: "6816391",
    Address: "agriculture produce markrt committee ,Mandhal,",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "15-Dec-23",
    "Registration Valid Upto": "14-Dec-28",
    phoneNo: "9370562355",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "APMC,nagbhid",
    name: "apmc,nagbhid",
    _id: "6701106",
    Address: "apmc,nagbhid, apmc nagbhid,nagbhid",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "28-Mar-23",
    "Registration Valid Upto": "27-Mar-28",
    phoneNo: "9422943283",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "arni",
    name: "A.PM.C. Arni",
    _id: "6761670",
    Address: "A.PM.C. Arni Tq. Arni.Dist.yawatmal,",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "25-Jul-23",
    "Registration Valid Upto": "24-Jul-28",
    phoneNo: "9975049260",
    Status: "Active",
    type: "hot",
    location: [],
  },
  {
    ownerName: "B T Kadlag Construction Private Limited",
    name: "B T KADLAG CONSTRUCTION PVT LTD",
    _id: "6846901",
    Address: "Godown No 1 and 2,, Gat no 558, Nanegao, Palse",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "7598",
    "Registration Date": "29-Jan-24",
    "Registration Valid Upto": "28-Jan-29",
    phoneNo: "9822199469",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "babhulgaon",
    name: "AMPC BABHULGAON",
    _id: "6775357",
    Address:
      "AT BABHULGAON DHAMANGAON RODE BABHULGAON, AT BABHULGAON DHAMANGAON RODE BABHULGAON",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "1147",
    "Registration Date": "23-Aug-23",
    "Registration Valid Upto": "22-Aug-28",
    phoneNo: "9403259988",
    Status: "Active",
    type: "cold",
    location: [],
  },
  {
    ownerName: "BLACKSTONE LOGISTICS PRIVATE LIMITED",
    name: "BLACKSTONE LOGISTICS PRIVATE LIMITED",
    _id: "6888846",
    Address: "Akola Bypass, Temburna Phata Khamgoan,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "35000",
    "Registration Date": "18-Mar-24",
    "Registration Valid Upto": "17-Sep-28",
    phoneNo: "8999015267",
    Status: "Active",
    type: "hot",
    location: [],
  },
];
