const warehouseDetailData = [
  {
    ownerName: "A.P.M.C.MALKAPUR",
    name: "APMC MALKAPUR",
    address: "BELAD YARD ,MALKAPUR,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "04-Jul-23",
    registrationValidUpto: "03-Jul-28",
    phoneNo: "9960783901",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.2746815, 74.1886849],
    price: 3639,
    email: "apmcmalkapur735@gmail.com",
    username: "onvywgcu",
    password: "Bangalore",
    occupied: "179",
    typeOfCrop: ["jute", "papaya", "cotton"],
  },
  {
    ownerName: "AGRICULTURAL PRODUCE MARKET COMMITTEE",
    name: "KRUSHI UTTPANA BAZAR SAMITI TULJAPUR",
    address: "Latur road Market yard,",
    city: "Osmanabad",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "27-Jul-23",
    registrationValidUpto: "26-Jul-28",
    phoneNo: "9975720584",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.00804, 76.07011],
    price: 4636,
    email: "krushiuttpanabazarsamitituljapur612@example.com",
    username: "gkdtzyyz",
    password: "Bangalore",
    occupied: "87",
    typeOfCrop: ["blackgram", "apple", "pomegranate"],
  },
  {
    ownerName: "Agricultural Produce Market Committee Baramati",
    name: "Agricultural Produce Market Committee Baramati",
    address: "Indapur Road, Market Yard",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "18-Jan-24",
    registrationValidUpto: "17-Jan-29",
    phoneNo: "9860305093",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.15174, 74.57767],
    price: 4161,
    email: "agriculturalproducemarketcommitteebaramati536@hotmail.com",
    username: "ipmmjevx",
    password: "Bangalore",
    occupied: "257",
    typeOfCrop: ["mango", "cotton", "watermelon"],
  },
  {
    ownerName: "Agricultural Produce Market Committee Manchar",
    name: "Agricultural Produce Market Committee Manchar",
    address: "Market yard Manchar,",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "19-Feb-24",
    registrationValidUpto: "18-Feb-29",
    phoneNo: "9922861133",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.00436, 73.94346],
    price: 2271,
    email: "agriculturalproducemarketcommitteemanchar24@example.com",
    username: "hcnvirex",
    password: "Bangalore",
    occupied: "251",
    typeOfCrop: ["watermelon", "orange", "mungbean", "chickpea"],
  },
  {
    ownerName:
      "Agricultural Produce Market Committee Nandura Tq Nandura Dist Budhana",
    name: "Agricultural Produce Market Committee Nandura",
    address: "TQ NANDURA, DIST BULDHANA",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "30-Jun-23",
    registrationValidUpto: "29-Jun-28",
    phoneNo: "9022118473",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.8372567, 76.4600208],
    price: 2896,
    email: "agriculturalproducemarketcommitteenandura960@hotmail.com",
    username: "qmxdowpo",
    password: "Bangalore",
    occupied: "361",
    typeOfCrop: ["coffee", "kidneybeans", "coconut", "orange", "apple"],
  },
  {
    ownerName: "Agricultural Produce Market Committee, Balapur",
    name: "APMC Balapur",
    address: "Sub Yard Wadegaon, Balapur Patur Road",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "19-Jun-23",
    registrationValidUpto: "18-Jun-28",
    phoneNo: "9370543764",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.66612, 76.77386],
    price: 3756,
    email: "apmcbalapur771@example.com",
    username: "unijytmz",
    password: "Bangalore",
    occupied: "288",
    typeOfCrop: ["muskmelon", "lentil", "orange"],
  },
  {
    ownerName: "agriculture produce market committee,goregaon",
    name: "APMC,Goregaon",
    address: "agriculture produce market committee,goregaon,",
    city: "Gondiya",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "22-Feb-23",
    registrationValidUpto: "21-Feb-28",
    phoneNo: "7507277558",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.15483, 73.29147],
    price: 3404,
    email: "apmc,goregaon799@yahoo.com",
    username: "npbkvkrp",
    password: "Bangalore",
    occupied: "110",
    typeOfCrop: ["pomegranate", "mothbeans", "jute", "grapes", "papaya"],
  },
  {
    ownerName: "agriculture produce market committee,hinganghat.",
    name: "Agriculture produce market committee, Hinganghat",
    address: "APMC, Hinganghat,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "06-Feb-24",
    registrationValidUpto: "05-Feb-29",
    phoneNo: "9860864627",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.54765, 78.84033],
    price: 3812,
    email: "agricultureproducemarketcommittee,hinganghat168@gmail.com",
    username: "myvmxksv",
    password: "Bangalore",
    occupied: "270",
    typeOfCrop: ["muskmelon", "chickpea", "blackgram"],
  },
  {
    ownerName: "APMC ,CHANDRAPUR",
    name: "APMC,chandrapur",
    address: "APMC,datala road ,chandrapur,",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "01-Mar-23",
    registrationValidUpto: "28-Feb-28",
    phoneNo: "9822711612",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.9426621, 79.8956424],
    price: 4077,
    email: "apmc,chandrapur800@hotmail.com",
    username: "diemmnri",
    password: "Bangalore",
    occupied: "158",
    typeOfCrop: ["mango", "muskmelon", "grapes", "papaya", "kidneybeans"],
  },
  {
    ownerName: "APMC ,pauni",
    name: "APMC Pauni",
    address: "Bhaitalawa ward Pauni, Pauni",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "06-Mar-23",
    registrationValidUpto: "05-Mar-28",
    phoneNo: "9881569891",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.79205, 79.63583],
    price: 1052,
    email: "apmcpauni686@yahoo.com",
    username: "shozfkkp",
    password: "Bangalore",
    occupied: "289",
    typeOfCrop: [
      "muskmelon",
      "kidneybeans",
      "watermelon",
      "lentil",
      "pigeonpeas",
    ],
  },
  {
    ownerName: "APMC ,Tumsar",
    name: "APMC ,tumsar",
    address: "agriculture produce market committee ,tumsar,",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "1147",
    registrationDate: "03-Mar-23",
    registrationValidUpto: "02-Mar-28",
    phoneNo: "7666759424",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.38333, 79.73333],
    price: 3233,
    email: "apmc,tumsar459@gmail.com",
    username: "zygsrnun",
    password: "Bangalore",
    occupied: "10",
    typeOfCrop: ["mungbean", "lentil", "pomegranate", "watermelon"],
  },
  {
    ownerName: "APMC LAsalgaon",
    name: "APMC Lasalgaon",
    address: "Vinchur,",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "01-May-23",
    registrationValidUpto: "30-Apr-28",
    phoneNo: "7387670813",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.14384, 74.23836],
    price: 1257,
    email: "apmclasalgaon761@example.com",
    username: "biqjtgsd",
    password: "Bangalore",
    occupied: "227",
    typeOfCrop: [
      "pomegranate",
      "kidneybeans",
      "watermelon",
      "chickpea",
      "maize",
    ],
  },
  {
    ownerName: "APMC Malegaon",
    name: "APMC Malegaon",
    address: "Main Market Yard Camp Road,",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "27-Jul-23",
    registrationValidUpto: "26-Jul-28",
    phoneNo: "7385572105",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.5537, 74.52881],
    price: 4724,
    email: "apmcmalegaon29@hotmail.com",
    username: "aodkpncw",
    password: "Bangalore",
    occupied: "298",
    typeOfCrop: ["maize", "lentil", "jute", "mango", "mungbean"],
  },
  {
    ownerName: "APMC Shrigonda",
    name: "APMC Shrigonda",
    address: "Market Yard Shrigonda, Duand-Jamkhed Road",
    city: "Ahmadnagar",
    state: "MAHARASHTRA",
    capacity: "1000",
    registrationDate: "14-Feb-24",
    registrationValidUpto: "13-Feb-29",
    phoneNo: "7028839989",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.61527, 74.69895],
    price: 4005,
    email: "apmcshrigonda418@yahoo.com",
    username: "pwaxxjzr",
    password: "Bangalore",
    occupied: "155",
    typeOfCrop: ["mango", "orange", "coffee", "lentil"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "CW Nanded ( Santosh Warehouse)",
    address: "Block No 178, Bhaygaon Road, Tuppa Nanded",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "24522",
    registrationDate: "07-Jun-21",
    registrationValidUpto: "06-Jun-26",
    phoneNo: "9960420107",
    status: "Inactive",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.16023, 77.31497],
    price: 1011,
    email: "cwnanded(santoshwarehouse)175@yahoo.com",
    username: "yaaygqyv",
    password: "Bangalore",
    occupied: "6112",
    typeOfCrop: ["grapes", "papaya", "jute", "coconut", "watermelon"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "Kolhapur-II",
    address: "A-3,MIDC,Gokulshirgaon,Kolhapur,",
    city: "Kolhapur",
    state: "MAHARASHTRA",
    capacity: "20000",
    registrationDate: "31-Mar-21",
    registrationValidUpto: "30-Mar-26",
    phoneNo: "7767089708",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [16.6796885, 74.4681136],
    price: 1003,
    email: "kolhapur-ii434@hotmail.com",
    username: "axmutjww",
    password: "Bangalore",
    occupied: "5993",
    typeOfCrop: ["pomegranate", "mango", "pigeonpeas", "grapes", "jute"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "CENTRAL WAREHOUSE, SANGLI",
    address: "3RD LANE, MARKET YARD, SANGLI",
    city: "Sangli",
    state: "MAHARASHTRA",
    capacity: "16060",
    registrationDate: "26-Dec-23",
    registrationValidUpto: "25-Dec-28",
    phoneNo: "9921508544",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [16.85438, 74.56417],
    price: 1404,
    email: "centralwarehouse,sangli372@yahoo.com",
    username: "mmmpeqpo",
    password: "Bangalore",
    occupied: "4690",
    typeOfCrop: ["mothbeans", "mungbean", "watermelon", "chickpea"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "Central Warehouse Amravati",
    address: "Krishna Nagar Post Office, New Cotton Market Road,Amravati",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "28920",
    registrationDate: "22-Feb-24",
    registrationValidUpto: "21-Feb-29",
    phoneNo: "9158249847",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.93333, 77.75],
    price: 3740,
    email: "centralwarehouseamravati635@example.com",
    username: "aobemsjl",
    password: "Bangalore",
    occupied: "11544",
    typeOfCrop: ["rice", "apple", "muskmelon", "blackgram"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "CENTRAL WAREHOUSING CORPORATION WASHIM (PEG)",
    address:
      "C/o :- RABIA LOGISTICS PVT LTD, DAGAD UMRA FATA WASHIM-PUSAD ROAD",
    city: "Washim",
    state: "MAHARASHTRA",
    capacity: "30000",
    registrationDate: "18-Jun-21",
    registrationValidUpto: "17-Jun-26",
    phoneNo: "8999015267",
    status: "Inactive",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.11152, 77.13221],
    price: 4860,
    email: "centralwarehousingcorporationwashim(peg)351@yahoo.com",
    username: "sadudbmb",
    password: "Bangalore",
    occupied: "6274",
    typeOfCrop: ["maize", "blackgram", "papaya"],
  },
  {
    ownerName: "Central Warehousing Corporation",
    name: "CENTRAL WAREHOUSE YAVATMAL",
    address: "DHAMANGAON ROAD, NEAR OCTROI CHECK POST",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "23714",
    registrationDate: "26-Dec-23",
    registrationValidUpto: "25-Dec-28",
    phoneNo: "9372309019",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.15, 78.35],
    price: 1961,
    email: "centralwarehouseyavatmal698@outlook.com",
    username: "dyxouybg",
    password: "Bangalore",
    occupied: "606",
    typeOfCrop: ["coconut", "rice", "mungbean"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Daryapur",
    address: "Mauze-Banosa, Near ITI, Daryapur,",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "6000",
    registrationDate: "26-May-23",
    registrationValidUpto: "25-May-28",
    phoneNo: "8805017485",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.9249, 77.32622],
    price: 2254,
    email: "maharashtra statewarehousingcorporation,daryapur437@hotmail.com",
    username: "uawbldow",
    password: "Bangalore",
    occupied: "1372",
    typeOfCrop: ["muskmelon", "orange", "chickpea"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Risod",
    address: "APMC, Market Yard, Risod,",
    city: "Washim",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9881751896",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.97549, 76.78844],
    price: 4022,
    email: "maharashtra statewarehousingcorporation,risod974@gmail.com",
    username: "oszexqmy",
    password: "Bangalore",
    occupied: "339",
    typeOfCrop: ["orange", "grapes", "pomegranate", "mothbeans", "chickpea"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Panvel (Multi Story)",
    address:
      "Maharashtra state Warehousing Corporation, Survey No. 437, Plot No. 465, Raigad Bazar, APMC Market Yard, Panvel",
    city: "Raigarh",
    state: "MAHARASHTRA",
    capacity: "8100",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "8149199752",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.98878, 73.11013],
    price: 2505,
    email: "panvel(multistory)419@yahoo.com",
    username: "archuswq",
    password: "Bangalore",
    occupied: "2991",
    typeOfCrop: ["mungbean", "banana", "grapes", "lentil", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "GANGAKHED",
    address: "PLOT NO.B-2, MIDC AREA,, GANGAKHED",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "7200",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9850611382",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.9130998, 76.7557068],
    price: 4376,
    email: "gangakhed992@yahoo.com",
    username: "selcdndt",
    password: "Bangalore",
    occupied: "155",
    typeOfCrop: ["lentil", "rice", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "NANDGAON",
    address: "APMC MARKET YARD, NANDGAON",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "1800",
    registrationDate: "29-May-22",
    registrationValidUpto: "28-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.3335523, 74.6707137],
    price: 2771,
    email: "nandgaon132@yahoo.com",
    username: "tjyazury",
    password: "Bangalore",
    occupied: "137",
    typeOfCrop: ["coconut", "papaya", "banana"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Warora",
    address:
      "Maharashtra state warehousing Corporation Warora, Near Saraf Factory,Warora ,Dist-Chandrapur Pin-442907",
    city: "Chandrapur",
    state: "MAHARASHTRA",
    capacity: "9880",
    registrationDate: "25-Nov-19",
    registrationValidUpto: "24-Nov-24",
    phoneNo: "9405943202",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.23014, 79.00161],
    price: 1579,
    email: "mswcwarora785@outlook.com",
    username: "xkyhxxor",
    password: "Bangalore",
    occupied: "98",
    typeOfCrop: ["muskmelon", "lentil", "banana", "mothbeans", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Tirthpuri",
    address: "MSWC, Tirthpuri, Taluka Ghansangavi,, Jalna -431209",
    city: "Jalna",
    state: "MAHARASHTRA",
    capacity: "1580",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "7588957049",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.4396245, 75.9237956],
    price: 2888,
    email: "tirthpuri15@yahoo.com",
    username: "jfkuyfyz",
    password: "Bangalore",
    occupied: "74",
    typeOfCrop: ["muskmelon", "pigeonpeas", "jute", "papaya"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Tumsar",
    address: "APMC, Market Yard, Tumsar",
    city: "Bhandara",
    state: "MAHARASHTRA",
    capacity: "7956",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9158679823",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.7111225, 79.8641448],
    price: 4147,
    email: "tumsar607@hotmail.com",
    username: "inzkgngn",
    password: "Bangalore",
    occupied: "1808",
    typeOfCrop: ["watermelon", "maize", "lentil", "pomegranate", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Godown Jalna",
    address:
      "Near Government godown, Near Bus Stand, Raut Nagar, Jalna -431203",
    city: "Jalna",
    state: "MAHARASHTRA",
    capacity: "8850",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "8788294872",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.84102, 75.88636],
    price: 1450,
    email: "citygodownjalna294@outlook.com",
    username: "muuzqovq",
    password: "Bangalore",
    occupied: "432",
    typeOfCrop: ["mango", "blackgram", "muskmelon", "kidneybeans", "lentil"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "KALWAN",
    address: "Market Yard, Kalwan, KALWAN",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "3500",
    registrationDate: "24-May-22",
    registrationValidUpto: "23-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.5293817, 73.9521683],
    price: 3894,
    email: "kalwan775@gmail.com",
    username: "xqewllig",
    password: "Bangalore",
    occupied: "269",
    typeOfCrop: ["lentil", "mungbean", "orange", "blackgram", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "UMARAGA",
    address: "EKONDI ROAD,, MARKET YARD",
    city: "Osmanabad",
    state: "MAHARASHTRA",
    capacity: "3377",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9423326150",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.8406534, 76.5885554],
    price: 1807,
    email: "umaraga706@hotmail.com",
    username: "frmxfkei",
    password: "Bangalore",
    occupied: "665",
    typeOfCrop: ["papaya", "mungbean", "pomegranate", "maize"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "LASALGAON",
    address: "MARKET YARD, KOTAMGAON ROAD",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "4000",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.1426837, 74.2377507],
    price: 1048,
    email: "lasalgaon880@outlook.com",
    username: "nmhvlsus",
    password: "Bangalore",
    occupied: "288",
    typeOfCrop: ["chickpea", "mango", "banana", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC BARAMATI",
    address: "MIDC ,BARAMATI,",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "15819",
    registrationDate: "24-May-22",
    registrationValidUpto: "23-May-27",
    phoneNo: "9158001058",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.15174, 74.57767],
    price: 4341,
    email: "mswcbaramati751@gmail.com",
    username: "dyuyzfts",
    password: "Bangalore",
    occupied: "1980",
    typeOfCrop: ["muskmelon", "apple", "kidneybeans", "papaya", "lentil"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Umarkhed",
    address: "Mahagaon Road, Umarkhed,",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "8280",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "7507550099",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.60144, 77.68878],
    price: 2527,
    email: "maharashtra statewarehousingcorporation,umarkhed88@hotmail.com",
    username: "ludadbxs",
    password: "Bangalore",
    occupied: "1776",
    typeOfCrop: ["cotton", "banana", "mungbean", "jute"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Malegaon (Washim)",
    address: "APMC, Near Rest House, Malegaon (Washim),",
    city: "Washim",
    state: "MAHARASHTRA",
    capacity: "2850",
    registrationDate: "26-Sep-22",
    registrationValidUpto: "25-Sep-27",
    phoneNo: "9970171187",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.5537, 74.52881],
    price: 1191,
    email:
      "maharashtra statewarehousingcorporation,malegaon(washim)288@hotmail.com",
    username: "tcgpctdw",
    password: "Bangalore",
    occupied: "763",
    typeOfCrop: ["coconut", "jute", "grapes", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Ahmednagar city",
    address: "WAKODI RAOD, BHAWANI NAGAR, MARKET YARD, AHMEDNAGAR,",
    city: "Ahmadnagar",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "07-Jun-22",
    registrationValidUpto: "06-Jun-27",
    phoneNo: "9822347088",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.09457, 74.73843],
    price: 3817,
    email: "mswcahmednagarcity863@hotmail.com",
    username: "vooktxyj",
    password: "Bangalore",
    occupied: "818",
    typeOfCrop: ["pigeonpeas", "rice", "muskmelon", "coconut", "jute"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC PANDHARPUR",
    address: "KORTI ROAD, IN FRONT OF KRUSHI OFFICE",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "16424",
    registrationDate: "25-May-22",
    registrationValidUpto: "24-May-27",
    phoneNo: "9158001342",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.67924, 75.33098],
    price: 2184,
    email: "mswcpandharpur935@yahoo.com",
    username: "cspvoxtj",
    password: "Bangalore",
    occupied: "5991",
    typeOfCrop: ["chickpea", "blackgram", "mothbeans", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, OSMANABAD",
    address: "Marketyard, Near Tuljapur Naka, Osmanabad",
    city: "Osmanabad",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "07-Jun-22",
    registrationValidUpto: "06-Jun-27",
    phoneNo: "8208543965",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.18158, 76.03889],
    price: 1277,
    email: "maharashtra statewarehousingcorporation,osmanabad680@gmail.com",
    username: "anzkobeg",
    password: "Bangalore",
    occupied: "1193",
    typeOfCrop: ["banana", "lentil", "kidneybeans", "watermelon", "orange"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Warud",
    address: "Nagpur Road, Roshankhed Phata,",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "7650",
    registrationDate: "19-May-22",
    registrationValidUpto: "18-May-27",
    phoneNo: "8149641881",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.47076, 78.26858],
    price: 4362,
    email: "maharashtra statewarehousingcorporation,warud647@gmail.com",
    username: "nvspqrfd",
    password: "Bangalore",
    occupied: "1853",
    typeOfCrop: ["muskmelon", "apple", "maize", "chickpea", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, PURNA",
    address: "NANDED-ROAD, PURNA",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "7510",
    registrationDate: "27-Jun-23",
    registrationValidUpto: "26-Jun-28",
    phoneNo: "9850030618",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.1798, 77.02595],
    price: 1373,
    email: "maharashtra statewarehousingcorporation,purna96@gmail.com",
    username: "gretdmnj",
    password: "Bangalore",
    occupied: "1580",
    typeOfCrop: ["blackgram", "mothbeans", "jute", "chickpea", "mungbean"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Indapur",
    address: "Marketyard APMC, Near hotel Khan Chacha",
    city: "Pune",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9881697171",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.3, 73.25],
    price: 3108,
    email: "mswcindapur663@yahoo.com",
    username: "uwgnyhqg",
    password: "Bangalore",
    occupied: "920",
    typeOfCrop: ["kidneybeans", "lentil", "orange", "maize", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "BODWAD",
    address: "APMC MARKET, MUKATINAGAR ROAD BODWAD",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.9034659, 76.0174431],
    price: 4109,
    email: "bodwad265@example.com",
    username: "davopuqn",
    password: "Bangalore",
    occupied: "3",
    typeOfCrop: ["kidneybeans", "lentil", "mothbeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Palghar",
    address:
      "Maharashtra state Warehousing Corporation, Nandore Naka, Near APMC, Manor Road",
    city: "Thane",
    state: "MAHARASHTRA",
    capacity: "5000",
    registrationDate: "29-May-22",
    registrationValidUpto: "28-May-27",
    phoneNo: "9029023752",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.684661, 72.8249112],
    price: 3757,
    email: "palghar176@hotmail.com",
    username: "sntknbvp",
    password: "Bangalore",
    occupied: "373",
    typeOfCrop: ["pomegranate", "watermelon", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "LONAND",
    address: "LONAND SATARA ROAD, KAPAD GAON, LONAND",
    city: "Satara",
    state: "MAHARASHTRA",
    capacity: "20197",
    registrationDate: "20-Jun-22",
    registrationValidUpto: "19-Jun-27",
    phoneNo: "9158001332",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.0387975, 74.186926],
    price: 3337,
    email: "lonand79@example.com",
    username: "tnfnocsr",
    password: "Bangalore",
    occupied: "970",
    typeOfCrop: ["watermelon", "coconut", "chickpea", "banana", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Wani (Yavatmal)",
    address: "Chandrapur Road, Wani (Yavatmal),",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "8550",
    registrationDate: "26-Sep-22",
    registrationValidUpto: "25-Sep-27",
    phoneNo: "9673527124",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.0639446, 78.9652282],
    price: 1343,
    email:
      "maharashtra statewarehousingcorporation,wani(yavatmal)315@outlook.com",
    username: "txltscmv",
    password: "Bangalore",
    occupied: "2703",
    typeOfCrop: ["grapes", "pigeonpeas", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation , Hinganghat",
    address: "Nagpur Hydrabad Highway, Hinganghat",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "6780",
    registrationDate: "27-Dec-22",
    registrationValidUpto: "26-Dec-27",
    phoneNo: "9423619102",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.54765, 78.84033],
    price: 2929,
    email: "maharashtra statewarehousingcorporation,hinganghat712@yahoo.com",
    username: "ptwhbrup",
    password: "Bangalore",
    occupied: "2490",
    typeOfCrop: ["mungbean", "lentil", "maize", "watermelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "NAVAPUR",
    address: "APMC MARKET, Opp. Sai Mandi, Main Road, Navapur",
    city: "Nandurbar",
    state: "MAHARASHTRA",
    capacity: "4000",
    registrationDate: "22-Jun-22",
    registrationValidUpto: "21-Jun-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.7904959, 72.6897825],
    price: 1714,
    email: "navapur58@example.com",
    username: "hviduzjp",
    password: "Bangalore",
    occupied: "1326",
    typeOfCrop: ["pigeonpeas", "banana", "kidneybeans", "chickpea", "papaya"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "JALNA BORKHEDI",
    address:
      "SHINDKHED RAJA ROAD, BORKHEDI DTST. JALNA, SHINDKHED RAJA ROAD, BORKHEDI DTST. JALNA",
    city: "Jalna",
    state: "MAHARASHTRA",
    capacity: "33611",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9158001317",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.8900471, 75.9953284],
    price: 2058,
    email: "jalnaborkhedi29@hotmail.com",
    username: "tjobnoaz",
    password: "Bangalore",
    occupied: "6345",
    typeOfCrop: ["coffee", "lentil", "grapes"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Nanded(MIDC)",
    address: "Plot No.B- 14-15 MIDC Area, Nanded",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "31209",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9158001335",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.16023, 77.31497],
    price: 2422,
    email: "mswcnanded(midc)722@yahoo.com",
    username: "muqzemgq",
    password: "Bangalore",
    occupied: "5144",
    typeOfCrop: ["papaya", "maize", "chickpea"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation",
    address:
      "Near Railway Station, Agriculture Markeing Produce Committe Katol",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "5850",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "7385785400",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.9329418, 77.7555379],
    price: 4710,
    email: "maharashtra statewarehousingcorporation545@yahoo.com",
    username: "lebbrtfi",
    password: "Bangalore",
    occupied: "1938",
    typeOfCrop: ["mothbeans", "kidneybeans", "orange"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "NAMPUR",
    address: "APMC MARKET YARD, APMC",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.7266441, 74.3129666],
    price: 2284,
    email: "nampur378@example.com",
    username: "igupmlfk",
    password: "Bangalore",
    occupied: "316",
    typeOfCrop: ["coffee", "coconut", "mango"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Malegaon",
    address: "CAMP ROAD, APMC MALEGAON, Malegaon",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "9600",
    registrationDate: "22-Jul-22",
    registrationValidUpto: "21-Jul-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.5896873, 74.5717573],
    price: 2563,
    email: "malegaon61@gmail.com",
    username: "xghjoqpi",
    password: "Bangalore",
    occupied: "2856",
    typeOfCrop: ["watermelon", "papaya", "rice"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, JINTUR",
    address: "WARUD ROAD, JINTUR",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "5220",
    registrationDate: "08-Aug-22",
    registrationValidUpto: "07-Aug-27",
    phoneNo: "9960851387",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.61186, 76.6874],
    price: 2499,
    email: "maharashtra statewarehousingcorporation,jintur980@gmail.com",
    username: "plzophor",
    password: "Bangalore",
    occupied: "840",
    typeOfCrop: ["blackgram", "pigeonpeas", "rice", "lentil", "mango"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "YAWAL",
    address: "YAWAL APMC, YAWAL",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "4250",
    registrationDate: "08-Jul-22",
    registrationValidUpto: "07-Jul-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.2260018, 75.6950825],
    price: 4374,
    email: "yawal836@gmail.com",
    username: "szvladdf",
    password: "Bangalore",
    occupied: "77",
    typeOfCrop: ["coffee", "blackgram", "cotton", "muskmelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, SAILU",
    address: "PATHRI ROAD, SAILU",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "7650",
    registrationDate: "24-May-22",
    registrationValidUpto: "23-May-27",
    phoneNo: "9673191509",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.45513, 76.43946],
    price: 2813,
    email: "maharashtra statewarehousingcorporation,sailu133@hotmail.com",
    username: "fkzztzzx",
    password: "Bangalore",
    occupied: "1349",
    typeOfCrop: ["papaya", "kidneybeans", "watermelon", "banana", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, JAWALA BAZAR",
    address: "APMC YARD, JAWALA BAZAR",
    city: "Hingoli",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9028980032",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.5, 76.0],
    price: 2215,
    email: "maharashtra statewarehousingcorporation,jawalabazar673@outlook.com",
    username: "ltmlelpz",
    password: "Bangalore",
    occupied: "1256",
    typeOfCrop: ["pigeonpeas", "lentil", "watermelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Majalgaon",
    address:
      "MSWC, Georai Road, Near Jining Presing, Post, PhulePimpalgaon, Majalgaon - 431131",
    city: "Bid",
    state: "MAHARASHTRA",
    capacity: "12640",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "8007242826",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.15599, 76.21152],
    price: 4377,
    email: "mswcmajalgaon660@gmail.com",
    username: "ungqzztw",
    password: "Bangalore",
    occupied: "3550",
    typeOfCrop: ["apple", "chickpea", "mothbeans", "grapes"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Darwha",
    address: "Arni Road, Darwha,",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "8000",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9766578305",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.30862, 77.7691],
    price: 3599,
    email: "maharashtra statewarehousingcorporation,darwha912@yahoo.com",
    username: "hsrnlets",
    password: "Bangalore",
    occupied: "2204",
    typeOfCrop: ["coffee", "pomegranate", "mango", "mungbean"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Hinganghat (APMC)",
    address: "Shivaji Market (APMC),, Hydrabad Highway, Hinganghat",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "9920",
    registrationDate: "26-Dec-22",
    registrationValidUpto: "25-Dec-27",
    phoneNo: "9423619102",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.54765, 78.84033],
    price: 3824,
    email:
      "maharashtra statewarehousingcorporation,hinganghat(apmc)511@yahoo.com",
    username: "bcznthwp",
    password: "Bangalore",
    occupied: "233",
    typeOfCrop: ["grapes", "kidneybeans", "chickpea", "watermelon", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "PACHORA",
    address: "PACHORA APMC,",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "27-Dec-22",
    registrationValidUpto: "26-Dec-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.6562575, 75.4011092],
    price: 4107,
    email: "pachora144@yahoo.com",
    username: "hngjbngk",
    password: "Bangalore",
    occupied: "463",
    typeOfCrop: ["maize", "chickpea", "muskmelon", "banana"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, MANWAT",
    address: "NEAR GOVT. REST-HOUSE, MANWAT",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "13050",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9423958800",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.30133, 76.49735],
    price: 4689,
    email: "maharashtra statewarehousingcorporation,manwat8@gmail.com",
    username: "zixfdfhs",
    password: "Bangalore",
    occupied: "2642",
    typeOfCrop: ["watermelon", "mango", "banana", "pomegranate", "rice"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "OZAR",
    address: "Mumbai Agra Haighway,",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "8050",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.7054212, 75.3280592],
    price: 1891,
    email: "ozar740@outlook.com",
    username: "gzexgrqx",
    password: "Bangalore",
    occupied: "1857",
    typeOfCrop: ["apple", "papaya", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Khamgaon (Warkhed)",
    address: "Shegaon Road, Khamgaon (Warkhed),",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "29040",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9158001330",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.70738, 76.56827],
    price: 1022,
    email:
      "maharashtra statewarehousingcorporation,khamgaon(warkhed)685@gmail.com",
    username: "esdbugxc",
    password: "Bangalore",
    occupied: "11297",
    typeOfCrop: ["coconut", "papaya", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Chandur Bazar",
    address: "APMC, Market Yard, Chandur Bazar,",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "10800",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9527726322",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.2391, 77.74703],
    price: 2228,
    email: "maharashtra statewarehousingcorporation,chandurbazar416@gmail.com",
    username: "ryswdahm",
    password: "Bangalore",
    occupied: "3650",
    typeOfCrop: ["lentil", "papaya", "cotton", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "CHALISGAON",
    address: "CHALISGAON APMC,",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "12800",
    registrationDate: "05-Jul-22",
    registrationValidUpto: "04-Jul-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.5023656, 74.96557],
    price: 3983,
    email: "chalisgaon29@outlook.com",
    username: "uatdldfx",
    password: "Bangalore",
    occupied: "3619",
    typeOfCrop: ["lentil", "orange", "jute", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, DEGLUR",
    address: "APMC MARKETYARD, BEHIND SHETKARI NIVAS, DEGLUR, Deglur",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "14-Jul-23",
    registrationValidUpto: "13-Jul-28",
    phoneNo: "9764669778",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.54829, 77.57695],
    price: 2384,
    email: "maharashtra statewarehousingcorporation,deglur998@gmail.com",
    username: "vxvqpwub",
    password: "Bangalore",
    occupied: "287",
    typeOfCrop: ["muskmelon", "maize", "chickpea", "jute"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Malkapur",
    address: "Nandura Road, Malkapur,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "6200",
    registrationDate: "26-Sep-22",
    registrationValidUpto: "25-Sep-27",
    phoneNo: "9921472770",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.8856, 76.20371],
    price: 3561,
    email: "maharashtra statewarehousingcorporation,malkapur593@hotmail.com",
    username: "crdfjpcq",
    password: "Bangalore",
    occupied: "1106",
    typeOfCrop: ["chickpea", "watermelon", "jute"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Sillod",
    address:
      "MSWC, Aurangabad-Ajanta-Jalgaon Road, Sillod, Tal Sillod, Dist Aurangabad",
    city: "Aurangabad",
    state: "MAHARASHTRA",
    capacity: "4740",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9850078978",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.30303, 75.65284],
    price: 3971,
    email: "mswcsillod567@outlook.com",
    username: "aueznrue",
    password: "Bangalore",
    occupied: "1398",
    typeOfCrop: ["chickpea", "rice", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation",
    address: "Agriculture Produce Market Committee, Market Yard Savner",
    city: "Nagpur",
    state: "MAHARASHTRA",
    capacity: "3150",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9764919922",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.9329418, 77.7555379],
    price: 4770,
    email: "maharashtra statewarehousingcorporation13@yahoo.com",
    username: "gxbrqwfi",
    password: "Bangalore",
    occupied: "826",
    typeOfCrop: ["muskmelon", "grapes", "banana", "papaya"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Lasur ( Station",
    address: "MSWC, APMC Area, Lasur (station), Taluka- Gangapur, Aurangabad-",
    city: "Aurangabad",
    state: "MAHARASHTRA",
    capacity: "4180",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "9860820981",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.9308686, 75.0127245],
    price: 4870,
    email: "lasur(station695@hotmail.com",
    username: "ipijocbi",
    password: "Bangalore",
    occupied: "25",
    typeOfCrop: ["mothbeans", "watermelon", "mango", "banana"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Akola",
    address: "N-66, MIDC Area, Phase-4, Akola,",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "20000",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "9403047251",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.5, 77.16667],
    price: 3130,
    email: "maharashtra statewarehousingcorporation,akola214@example.com",
    username: "kzbjsrhl",
    password: "Bangalore",
    occupied: "1165",
    typeOfCrop: ["cotton", "coconut", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Tasgaon",
    address: "Market Yard Tasgaon,",
    city: "Sangli",
    state: "MAHARASHTRA",
    capacity: "3480",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9860345007",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [17.0904859, 74.6832675],
    price: 3264,
    email: "tasgaon377@yahoo.com",
    username: "qlkhjgkz",
    password: "Bangalore",
    occupied: "527",
    typeOfCrop: ["apple", "coffee", "grapes", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Karmala",
    address: '"Jamkhed Road, Karmala 413203", "M.S.W.C Market Yard,"',
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "8369278804",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.4077, 75.19386],
    price: 2753,
    email: "mswckarmala248@example.com",
    username: "kopsoiri",
    password: "Bangalore",
    occupied: "674",
    typeOfCrop: ["blackgram", "maize", "kidneybeans", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "BEED",
    address: "PLOT NO.47,48, MIDC AREA BEED TQ.DIST.BEED",
    city: "Bid",
    state: "MAHARASHTRA",
    capacity: "8726",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "8329768566",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.9918442, 75.909784],
    price: 4818,
    email: "beed402@hotmail.com",
    username: "lzdlfqdh",
    password: "Bangalore",
    occupied: "3082",
    typeOfCrop: ["mango", "kidneybeans", "pomegranate", "cotton", "rice"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, DHARMABAD",
    address: "RATNALI ROAD,, DHARMABAD",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "8830758165",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.89116, 77.8494],
    price: 3292,
    email: "maharashtra statewarehousingcorporation,dharmabad647@hotmail.com",
    username: "bwdrtkxf",
    password: "Bangalore",
    occupied: "1829",
    typeOfCrop: ["watermelon", "blackgram", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Hinganghat",
    address: "Nagpur Hydarabad Highway, Hinganghat",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "19050",
    registrationDate: "22-Sep-22",
    registrationValidUpto: "21-Sep-27",
    phoneNo: "9423619102",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.54765, 78.84033],
    price: 2364,
    email: "maharashtra statewarehousingcorporation,hinganghat509@example.com",
    username: "qnahtole",
    password: "Bangalore",
    occupied: "4891",
    typeOfCrop: ["lentil", "rice", "cotton", "jute", "apple"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "JALGAON H-14",
    address: "PLOT NO.H14,MIDC AREA,JALGAON, JALGAON",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "61803",
    registrationDate: "15-May-22",
    registrationValidUpto: "14-May-27",
    phoneNo: "9579713020",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.8455632, 75.1133537],
    price: 4538,
    email: "jalgaonh-1497@hotmail.com",
    username: "ijulamay",
    password: "Bangalore",
    occupied: "11580",
    typeOfCrop: ["banana", "blackgram", "chickpea"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation",
    address: "Agricultural Produce Market Committee, Gokul Nagar , Gadchiroli",
    city: "Gadchiroli",
    state: "MAHARASHTRA",
    capacity: "4000",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "7875144303",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.9329418, 77.7555379],
    price: 4873,
    email: "maharashtra statewarehousingcorporation443@gmail.com",
    username: "qlclwpbo",
    password: "Bangalore",
    occupied: "638",
    typeOfCrop: ["mango", "banana", "mungbean", "chickpea"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC, AHMEDPUR",
    address: "MIDC Area, Nanded Road, AHMEDPUR",
    city: "Latur",
    state: "MAHARASHTRA",
    capacity: "5100",
    registrationDate: "25-May-22",
    registrationValidUpto: "24-May-27",
    phoneNo: "9975790190",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.70622, 76.93731],
    price: 3268,
    email: "mswc,ahmedpur434@example.com",
    username: "vmktupvd",
    password: "Bangalore",
    occupied: "1561",
    typeOfCrop: ["pomegranate", "apple", "mungbean", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Jaysingpur",
    address: "Market yard,Near Pol Factory, Jaysingpur,",
    city: "Kolhapur",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "9175927336",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [16.7789886, 74.5564244],
    price: 4331,
    email: "jaysingpur321@example.com",
    username: "dgtryjgo",
    password: "Bangalore",
    occupied: "837",
    typeOfCrop: ["coconut", "cotton", "watermelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "NANDURBAR",
    address: "G.T.P.college Road Nandurbar, Opp Shani mandir, Nandurbar",
    city: "Nandurbar",
    state: "MAHARASHTRA",
    capacity: "11520",
    registrationDate: "07-Jun-22",
    registrationValidUpto: "06-Jun-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.5141622, 74.5405513],
    price: 1127,
    email: "nandurbar543@gmail.com",
    username: "esdcmdhi",
    password: "Bangalore",
    occupied: "1092",
    typeOfCrop: ["rice", "mothbeans", "pigeonpeas", "muskmelon", "grapes"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Sangola",
    address: "APMC ,Market Yard,",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "2980",
    registrationDate: "25-Nov-19",
    registrationValidUpto: "24-Nov-24",
    phoneNo: "9420662254",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.43948, 75.19379],
    price: 1584,
    email: "mswcsangola23@outlook.com",
    username: "cddpkwqp",
    password: "Bangalore",
    occupied: "172",
    typeOfCrop: ["mothbeans", "mungbean", "lentil", "pomegranate", "rice"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Ichalkaranji",
    address:
      "Market Yard Sangli Road Ichalkaranji, Market Yard Sangli Road Ichalkaranji",
    city: "Kolhapur",
    state: "MAHARASHTRA",
    capacity: "3000",
    registrationDate: "29-May-22",
    registrationValidUpto: "28-May-27",
    phoneNo: "9175927336",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [16.6959348, 74.4555755],
    price: 2951,
    email: "ichalkaranji223@gmail.com",
    username: "gfoyljcw",
    password: "Bangalore",
    occupied: "946",
    typeOfCrop: ["coffee", "blackgram", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Khamgaon city",
    address: "APMC, Market Yard, Khamgaon,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "3620",
    registrationDate: "26-Sep-22",
    registrationValidUpto: "25-Sep-27",
    phoneNo: "8855899877",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.70738, 76.56827],
    price: 2454,
    email: "maharashtra statewarehousingcorporation,khamgaoncity428@gmail.com",
    username: "wsyrvucy",
    password: "Bangalore",
    occupied: "1276",
    typeOfCrop: ["chickpea", "mungbean", "banana", "jute", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "AMBAD (NASHIK)",
    address: "H-105 MIDC, AMBAD NASHIK",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "2880",
    registrationDate: "08-Aug-22",
    registrationValidUpto: "07-Aug-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.9499946, 73.7431463],
    price: 4490,
    email: "ambad(nashik)929@yahoo.com",
    username: "asnwpupr",
    password: "Bangalore",
    occupied: "491",
    typeOfCrop: ["mango", "rice", "orange", "cotton"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corpration, Arvi",
    address: "Pulgaon Road, Arvi,",
    city: "Wardha",
    state: "MAHARASHTRA",
    capacity: "9000",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "9420246333",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.99645, 78.22868],
    price: 1520,
    email: "maharashtra statewarehousingcorpration,arvi531@hotmail.com",
    username: "dsgkrgcj",
    password: "Bangalore",
    occupied: "2320",
    typeOfCrop: ["rice", "papaya", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MANMAD",
    address: "APMC MARKET YARD, CHANWAD ROAD MANMAD",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "12900",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.2519828, 74.4392286],
    price: 3448,
    email: "manmad749@gmail.com",
    username: "vzklxpll",
    password: "Bangalore",
    occupied: "2479",
    typeOfCrop: ["orange", "chickpea", "pomegranate", "maize", "muskmelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Wai",
    address: "Plot no-B 50, Near Garware Company ,MIDC Wai",
    city: "Satara",
    state: "MAHARASHTRA",
    capacity: "7600",
    registrationDate: "11-Dec-19",
    registrationValidUpto: "10-Dec-24",
    phoneNo: "9860345007",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.95276, 73.89058],
    price: 4531,
    email: "mswcwai538@outlook.com",
    username: "yorcqtym",
    password: "Bangalore",
    occupied: "2820",
    typeOfCrop: ["rice", "watermelon", "maize", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Phaltan",
    address: "At Tambmal, Lonand - Phaltan Road, Post Farandwadi, Tal. Phalan",
    city: "Satara",
    state: "MAHARASHTRA",
    capacity: "8920",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "8830845445",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.9579342, 74.4142354],
    price: 2901,
    email: "phaltan316@yahoo.com",
    username: "xjdxntmt",
    password: "Bangalore",
    occupied: "649",
    typeOfCrop: ["cotton", "coffee", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "LOHARA (Y)",
    address: "MIDC Area, Lohara,",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "16364",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "9665234365",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.3933075, 78.4268689],
    price: 1705,
    email: "lohara(y)830@example.com",
    username: "rbesduld",
    password: "Bangalore",
    occupied: "4179",
    typeOfCrop: ["papaya", "jute", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC RATNAGIRI",
    address: "T-6 MIDC ,MIRJOLE BLOCK,, TAL & DIST. RATNAGIRI",
    city: "Ratnagiri",
    state: "MAHARASHTRA",
    capacity: "14260",
    registrationDate: "24-May-22",
    registrationValidUpto: "23-May-27",
    phoneNo: "8097537118",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.0, 73.5],
    price: 4147,
    email: "mswcratnagiri76@outlook.com",
    username: "oszqzrjn",
    password: "Bangalore",
    occupied: "3066",
    typeOfCrop: ["mango", "watermelon", "muskmelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "AKKALKOT",
    address: "Akkalkot, Akkalkot",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "7704",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "9175989021",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.515193, 76.212278],
    price: 1203,
    email: "akkalkot144@yahoo.com",
    username: "ssjqftai",
    password: "Bangalore",
    occupied: "2522",
    typeOfCrop: ["pigeonpeas", "maize", "cotton", "mothbeans", "papaya"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "SHAHADA",
    address: "BEHIND State BANK, MARKET YARD",
    city: "Nandurbar",
    state: "MAHARASHTRA",
    capacity: "5100",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.740052, 78.635796],
    price: 4390,
    email: "shahada210@example.com",
    username: "rrpbglgy",
    password: "Bangalore",
    occupied: "1302",
    typeOfCrop: ["jute", "banana", "pomegranate"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Lote Parshuram",
    address: "M.I.D.C Area lote (P) P.29,",
    city: "Ratnagiri",
    state: "MAHARASHTRA",
    capacity: "5830",
    registrationDate: "31-Jul-23",
    registrationValidUpto: "30-Jul-28",
    phoneNo: "8097537118",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.58437, 73.4979351],
    price: 4516,
    email: "loteparshuram470@outlook.com",
    username: "ajkoavwy",
    password: "Bangalore",
    occupied: "1085",
    typeOfCrop: ["lentil", "jute", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Vaijapur",
    address: "MSWC, Opp power house,, Aurangabad Rd, Vaijapur",
    city: "Aurangabad",
    state: "MAHARASHTRA",
    capacity: "6320",
    registrationDate: "27-Jun-23",
    registrationValidUpto: "26-Jun-28",
    phoneNo: "9860820981",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.92672, 74.7275],
    price: 2774,
    email: "mswcvaijapur785@gmail.com",
    username: "vcprstrd",
    password: "Bangalore",
    occupied: "191",
    typeOfCrop: ["coconut", "cotton", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, AUSA",
    address: "PLOT NO.B-11 MIDCI AUSA, AUSA",
    city: "Latur",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "27-Jun-23",
    registrationValidUpto: "26-Jun-28",
    phoneNo: "9579866338",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.24728, 76.4993],
    price: 1964,
    email: "maharashtra statewarehousingcorporation,ausa975@yahoo.com",
    username: "gvfqdzik",
    password: "Bangalore",
    occupied: "2077",
    typeOfCrop: ["orange", "jute", "banana", "cotton", "mango"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra State WAREHOUSING CORPORATION, PARBHANI-CITY",
    address: "Behind Zilha Parishad Parbhani, Near DSM Collage, PARBHANI",
    city: "Parbhani",
    state: "MAHARASHTRA",
    capacity: "6000",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9545011693",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.5, 76.75],
    price: 1274,
    email:
      "maharashtra statewarehousingcorporation,parbhani-city809@example.com",
    username: "pfzbdoho",
    password: "Bangalore",
    occupied: "589",
    typeOfCrop: ["apple", "coffee", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "UDGIRMSWC,A1MIDC Area, Loni,Nanded Road,Udgir",
    address: "MSWC,A1MIDC Area, Loni,Nanded Road,Udgir, UDGIR",
    city: "Latur",
    state: "MAHARASHTRA",
    capacity: "12300",
    registrationDate: "19-Sep-22",
    registrationValidUpto: "18-Sep-27",
    phoneNo: "9970640322",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.39258, 77.11756],
    price: 1851,
    email: "udgirmswc,a1midcarea,loni,nandedroad,udgir537@example.com",
    username: "poeddgfb",
    password: "Bangalore",
    occupied: "4036",
    typeOfCrop: ["blackgram", "orange", "grapes", "chickpea", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "KASODA",
    address: "APMC MARKET YARD, KASODA",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "30-Jun-22",
    registrationValidUpto: "29-Jun-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.8211306, 75.2956366],
    price: 2234,
    email: "kasoda982@yahoo.com",
    username: "wrsmkiol",
    password: "Bangalore",
    occupied: "162",
    typeOfCrop: ["maize", "pigeonpeas", "orange"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Karjat",
    address:
      "Maharashtra state Warehousing Corporation, Dahivali Krushi Utpanna Bazar Samiti, Market Yard",
    city: "Raigarh",
    state: "MAHARASHTRA",
    capacity: "1450",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9137308234",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.9107, 73.32354],
    price: 4417,
    email: "mswckarjat558@yahoo.com",
    username: "tuzfzzcp",
    password: "Bangalore",
    occupied: "365",
    typeOfCrop: ["watermelon", "orange", "coconut", "lentil"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, NANDED-city",
    address: "NANDED-HINGOLI ROAD, VASANT NAGER",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "5640",
    registrationDate: "23-Sep-22",
    registrationValidUpto: "22-Sep-27",
    phoneNo: "9823426019",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.16023, 77.31497],
    price: 3793,
    email: "maharashtra statewarehousingcorporation,nanded-city960@yahoo.com",
    username: "mxbktxhg",
    password: "Bangalore",
    occupied: "1614",
    typeOfCrop: ["mango", "coffee", "orange"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Pusad",
    address: "Dhankeshwar Road, Washim Road,",
    city: "Yavatmal",
    state: "MAHARASHTRA",
    capacity: "8000",
    registrationDate: "22-Sep-22",
    registrationValidUpto: "21-Sep-27",
    phoneNo: "9767960097",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.9089, 77.56825],
    price: 1732,
    email: "maharashtra statewarehousingcorporation,pusad248@example.com",
    username: "evkljjaf",
    password: "Bangalore",
    occupied: "947",
    typeOfCrop: ["coffee", "mungbean", "blackgram", "mango", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Telhara",
    address: "APMC, Market Yar, Telhara,",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "4800",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "8788101807",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.02694, 76.83889],
    price: 4634,
    email: "maharashtra statewarehousingcorporation,telhara5@gmail.com",
    username: "vlnakmlr",
    password: "Bangalore",
    occupied: "1841",
    typeOfCrop: ["chickpea", "coffee", "coconut"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MSWC Solapur",
    address: "PLOT NO.8, SIDDHESHWAR MARKET YARD,",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "5400",
    registrationDate: "13-Jun-22",
    registrationValidUpto: "12-Jun-27",
    phoneNo: "9960243003",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [17.75, 75.5],
    price: 4388,
    email: "mswcsolapur796@gmail.com",
    username: "dfupodmc",
    password: "Bangalore",
    occupied: "1129",
    typeOfCrop: ["mango", "lentil", "grapes"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Achalpur",
    address: "APMC, Market Yard, Achalpur,",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "5000",
    registrationDate: "22-Sep-22",
    registrationValidUpto: "21-Sep-27",
    phoneNo: "9604743185",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.25722, 77.50861],
    price: 1285,
    email: "maharashtra statewarehousingcorporation,achalpur492@example.com",
    username: "yomidkdc",
    password: "Bangalore",
    occupied: "706",
    typeOfCrop: ["maize", "coconut", "muskmelon", "cotton"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Akot",
    address: "APMC, Market Yard, Akot,",
    city: "Akola",
    state: "MAHARASHTRA",
    capacity: "3870",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "9146938353",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.09639, 77.05861],
    price: 4779,
    email: "maharashtra statewarehousingcorporation,akot890@gmail.com",
    username: "fmkpikhk",
    password: "Bangalore",
    occupied: "939",
    typeOfCrop: ["maize", "coconut", "grapes", "watermelon", "blackgram"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Nandgaon Kh.",
    address: "APMC, Market Yard, Amravati Road, Nadgaon Khandeshwar,",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "3600",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "8208231129",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.5964, 78.2077],
    price: 2101,
    email: "maharashtra statewarehousingcorporation,nandgaonkh.90@gmail.com",
    username: "cocjihug",
    password: "Bangalore",
    occupied: "57",
    typeOfCrop: ["grapes", "coffee", "maize", "cotton", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Mehekar",
    address: "APMC, Market Yard, Dongaon Road, Mehekar,",
    city: "Buldana",
    state: "MAHARASHTRA",
    capacity: "10000",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9881751896",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [20.1505, 76.56841],
    price: 3819,
    email: "maharashtra statewarehousingcorporation,mehekar425@yahoo.com",
    username: "raeydnnu",
    password: "Bangalore",
    occupied: "2403",
    typeOfCrop: ["cotton", "maize", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, KINWAT",
    address:
      "Mahur Rd., Co. Op. Cotton Ginning & Pressing Soc. Ltd. Kinwat, Tq. Kinwat, KINWAT",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "3150",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "7972962388",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.62368, 78.2],
    price: 3940,
    email: "maharashtra statewarehousingcorporation,kinwat513@outlook.com",
    username: "okczxqmx",
    password: "Bangalore",
    occupied: "1145",
    typeOfCrop: ["cotton", "lentil", "maize", "pomegranate"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MIRAJ",
    address:
      "Miraj Pandharpur road, Tasgaon Phata, Miraj, Gat No. 2233A, Malgaon,Miraj",
    city: "Sangli",
    state: "MAHARASHTRA",
    capacity: "14400",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9404716517",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [16.858516, 74.7108947],
    price: 2095,
    email: "miraj763@example.com",
    username: "lqqosisk",
    password: "Bangalore",
    occupied: "4188",
    typeOfCrop: ["kidneybeans", "chickpea", "grapes", "pomegranate", "lentil"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Takari",
    address: "Marketyard, Takari, Tal- Walwa,,",
    city: "Sangli",
    state: "MAHARASHTRA",
    capacity: "2980",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9096978970",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.4831623, 80.3577061],
    price: 3423,
    email: "takari297@hotmail.com",
    username: "nyatngmi",
    password: "Bangalore",
    occupied: "1015",
    typeOfCrop: ["lentil", "orange", "coffee"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "RAVER",
    address: "Near by ITI,Utkheda Road,Pal Phata, RAVER",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "5160",
    registrationDate: "28-May-22",
    registrationValidUpto: "27-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.2268818, 75.9985933],
    price: 1660,
    email: "raver955@gmail.com",
    username: "mtyyuyeg",
    password: "Bangalore",
    occupied: "1482",
    typeOfCrop: ["muskmelon", "rice", "pigeonpeas", "mango", "mungbean"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "DHARANGAON",
    address: "A.P.M.C MARKET, DHARANGAON",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "6600",
    registrationDate: "01-Jul-22",
    registrationValidUpto: "30-Jun-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.0283404, 75.367342],
    price: 4721,
    email: "dharangaon949@outlook.com",
    username: "zvbssskt",
    password: "Bangalore",
    occupied: "2406",
    typeOfCrop: ["coconut", "pigeonpeas", "grapes", "muskmelon", "cotton"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "CHOPDA",
    address: "APMC MARKET YARD, CHOPADA",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "4050",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.2771494, 75.3402197],
    price: 1038,
    email: "chopda136@gmail.com",
    username: "jrlgktzf",
    password: "Bangalore",
    occupied: "1189",
    typeOfCrop: ["lentil", "watermelon", "orange", "apple", "pomegranate"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "WANI NASHIK",
    address: "MULANE ROAD,WANI (N), WANI",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "05-Jul-22",
    registrationValidUpto: "04-Jul-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.99727, 73.79096],
    price: 4209,
    email: "waninashik617@yahoo.com",
    username: "bmljpaxy",
    password: "Bangalore",
    occupied: "633",
    typeOfCrop: ["maize", "coffee", "mungbean", "papaya"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "DHAMANGAON",
    address: "Near by DSMS Colloge, Dhamangaon, Dhamangaon",
    city: "Amravati",
    state: "MAHARASHTRA",
    capacity: "12043",
    registrationDate: "26-May-22",
    registrationValidUpto: "25-May-27",
    phoneNo: "8805060702",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [21.1773882, 76.2180723],
    price: 3599,
    email: "dhamangaon408@gmail.com",
    username: "wenohexm",
    password: "Bangalore",
    occupied: "1620",
    typeOfCrop: ["coconut", "coffee", "kidneybeans", "chickpea", "banana"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Partur",
    address:
      "MSWC, APMC Area, Pardgaon Road, Near Railway Track, Tal.Partur, Jalna 431501",
    city: "Jalna",
    state: "MAHARASHTRA",
    capacity: "5840",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "7588089986",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.4882762, 76.2606978],
    price: 4698,
    email: "partur331@hotmail.com",
    username: "shxuuzrx",
    password: "Bangalore",
    occupied: "1951",
    typeOfCrop: ["maize", "watermelon", "mothbeans", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "KHADKI AHMADNAGAR",
    address: '"At Khadki, Post-Khandala,, Tal-Nagar, Dist-Ahmednagar "',
    city: "Ahmadnagar",
    state: "MAHARASHTRA",
    capacity: "8944",
    registrationDate: "23-May-22",
    registrationValidUpto: "22-May-27",
    phoneNo: "9822148684",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [18.9589029, 74.7043477],
    price: 1748,
    email: "khadkiahmadnagar313@outlook.com",
    username: "wiqfbmpn",
    password: "Bangalore",
    occupied: "3415",
    typeOfCrop: ["mothbeans", "coffee", "grapes"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state Warehousing Corporation, Washim",
    address: "APMN, Market Yard, Near Railway Station, Washim,",
    city: "Washim",
    state: "MAHARASHTRA",
    capacity: "10950",
    registrationDate: "19-May-22",
    registrationValidUpto: "18-May-27",
    phoneNo: "9765439919",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [20.11152, 77.13221],
    price: 1154,
    email: "maharashtra statewarehousingcorporation,washim20@outlook.com",
    username: "agaxncra",
    password: "Bangalore",
    occupied: "795",
    typeOfCrop: ["jute", "grapes", "mothbeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "KUDAL",
    address: "Kudal, Kudal",
    city: "Sindhudurg",
    state: "MAHARASHTRA",
    capacity: "9821",
    registrationDate: "01-Jun-22",
    registrationValidUpto: "31-May-27",
    phoneNo: "9403322939",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [16.0635268, 73.8392416],
    price: 3929,
    email: "kudal401@example.com",
    username: "xkscapaj",
    password: "Bangalore",
    occupied: "1665",
    typeOfCrop: ["kidneybeans", "banana", "muskmelon", "rice", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "NAGAPUR AHMEDNAGAR",
    address: "P 153 NAGAPUR MIDC, AHMEDNAGAR, NEAR JIMKHANA",
    city: "Ahmadnagar",
    state: "MAHARASHTRA",
    capacity: "22854",
    registrationDate: "19-May-22",
    registrationValidUpto: "18-May-27",
    phoneNo: "9822858423",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.4659044, 74.9901867],
    price: 3505,
    email: "nagapurahmednagar329@outlook.com",
    username: "tlqwugjr",
    password: "Bangalore",
    occupied: "7966",
    typeOfCrop: ["kidneybeans", "banana", "muskmelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Parli Tokwadi",
    address: "PARLI BEED ROAD, TOKWADI",
    city: "Bid",
    state: "MAHARASHTRA",
    capacity: "15378",
    registrationDate: "15-May-22",
    registrationValidUpto: "14-May-27",
    phoneNo: "9763816355",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [18.8718947, 76.5013432],
    price: 3335,
    email: "parlitokwadi494@gmail.com",
    username: "rfubuppp",
    password: "Bangalore",
    occupied: "1049",
    typeOfCrop: ["coconut", "orange", "pomegranate", "kidneybeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Ashti",
    address:
      "MSWC, APMC Area ( Dhotar Joda), Taluka Partur, Partur, Jalna - 431507",
    city: "Jalna",
    state: "MAHARASHTRA",
    capacity: "2000",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "7588957049",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.2056584, 78.1827905],
    price: 2167,
    email: "ashti337@example.com",
    username: "syobbopz",
    password: "Bangalore",
    occupied: "227",
    typeOfCrop: ["watermelon", "muskmelon", "coconut", "pigeonpeas"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "JALGAON B-6",
    address: "AJANTHA ROAD, MIDC B-6 JALGAON",
    city: "Jalgaon",
    state: "MAHARASHTRA",
    capacity: "16600",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.042262, 76.533479],
    price: 4261,
    email: "jalgaonb-6688@hotmail.com",
    username: "xyctyvna",
    password: "Bangalore",
    occupied: "5627",
    typeOfCrop: ["lentil", "rice", "mothbeans"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "MUSALGAON (NASHIK)",
    address: "Plot No. 142/2,, MUSALGAON MIDC MUSALGAON",
    city: "Nashik",
    state: "MAHARASHTRA",
    capacity: "3000",
    registrationDate: "13-Aug-22",
    registrationValidUpto: "12-Aug-27",
    phoneNo: "8408882562",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [19.8346768, 74.0535946],
    price: 2068,
    email: "musalgaon(nashik)927@yahoo.com",
    username: "mnohgxqo",
    password: "Bangalore",
    occupied: "689",
    typeOfCrop: ["pomegranate", "apple", "jute", "papaya", "banana"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "CHINCHOLI (MIDC)",
    address: "B/10 CHINCHOLI MIDC,",
    city: "Solapur",
    state: "MAHARASHTRA",
    capacity: "21905",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9158008754",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [17.46483, 77.41895],
    price: 1221,
    email: "chincholi(midc)270@gmail.com",
    username: "amvevbfk",
    password: "Bangalore",
    occupied: "6563",
    typeOfCrop: ["pigeonpeas", "blackgram", "watermelon"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Maharashtra state WAREHOUSING CORPORATION, WAI BAZAR",
    address: "Mahur Kinwat Rd., APMC Market Yard Wai Bazar,, WAI BAZAR",
    city: "Nanded",
    state: "MAHARASHTRA",
    capacity: "3150",
    registrationDate: "30-May-22",
    registrationValidUpto: "29-May-27",
    phoneNo: "9960440933",
    status: "Active",
    type: ["hot"],
    image: "/images/warehouse_1.jpg",
    location: [21.5945, 77.1261],
    price: 4861,
    email: "maharashtra statewarehousingcorporation,waibazar464@yahoo.com",
    username: "yndhgvfi",
    password: "Bangalore",
    occupied: "275",
    typeOfCrop: ["lentil", "apple", "orange"],
  },
  {
    ownerName: "Maharashtra state Warehousing Corporation",
    name: "Georai",
    address: "MSWC, APMC Area,, Beed Road, Georai , Beed- 431127",
    city: "Bid",
    state: "MAHARASHTRA",
    capacity: "6820",
    registrationDate: "23-Jun-22",
    registrationValidUpto: "22-Jun-27",
    phoneNo: "8788575878",
    status: "Active",
    type: ["cold"],
    image: "/images/warehouse_1.jpg",
    location: [19.2625294, 75.7504928],
    price: 3108,
    email: "georai615@example.com",
    username: "kjiaxrdv",
    password: "Bangalore",
    occupied: "1738",
    typeOfCrop: ["papaya", "lentil", "mothbeans"],
  },
];
