"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./provider/provider";
import ReduxProvider from "./provider/reduxProvider";
import { SpeedInsights } from "@vercel/speed-insights/next"

import "./globals.css";
import Navbar from "@/components/navbar.component";

const inter = Inter({ subsets: ["latin"] });

// "use server";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Providers>
            <Navbar />
            {children}
            <SpeedInsights />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
